version: '3'

vars:
  ROOT:
    sh: realpath -m "{{.TASKFILE_DIR}}/../.."
  EGET_PROJECT_NAME: eget
  EGET_REPO_URL: https://github.com/zyedidia/eget.git
  EGET_LATEST_VERSION:
    sh: git ls-remote --tags --refs --sort="v:refname" {{.EGET_REPO_URL}} | tail -n1 | sed 's/.*\///'
  EGET_VERSION_TAG: '{{default .EGET_LATEST_VERSION .VERSION}}'
  EGET_MAIN_PATH: .
  EGET_DIST_DIR: "{{.ROOT}}/dist"
  EGET_BUILD_DIR: "{{.ROOT}}/build"

tasks:
  check:
    desc: Verify the metadata of .deb files for this app only
    cmds:
      - cmd: |
          echo "Checking artifacts for {{.EGET_PROJECT_NAME}} in {{.EGET_DIST_DIR}}..."
          echo "---------------------------------------------------"
          files=$(ls {{.EGET_DIST_DIR}}/{{.EGET_PROJECT_NAME}}*.deb 2>/dev/null)

          if [ -z "$files" ]; then
            echo "⚠️  No .deb files found for {{.EGET_PROJECT_NAME}}."
            exit 0
          fi

          for f in $files; do
            echo "📦 $(basename $f)"
            dpkg --info "$f" | grep -E "^ (Package|Version|Architecture):"
            echo "---------------------------------------------------"
          done
    silent: true

  build:
    desc: Build "{{.EGET_PROJECT_NAME}}" (Go)
    env:
      PROJECT_NAME: "{{.EGET_PROJECT_NAME}}"
      MAIN_PATH: "{{.EGET_MAIN_PATH}}"
      VERSION_TAG: "{{.EGET_VERSION_TAG}}"
      BUILD_DIR: "{{.EGET_BUILD_DIR}}"
      DIST_DIR: "{{.EGET_DIST_DIR}}"
    cmds:
      - echo "Building {{.EGET_PROJECT_NAME}}..."
      - cmd: |
          DIR="{{.EGET_BUILD_DIR}}/{{.EGET_PROJECT_NAME}}"
          DAYS={{default "7" .BUILDER_CACHE_MAX_AGE_DAYS}}
          if [ -d "$DIR" ] && [ -z "$(find "$DIR" -maxdepth 0 -mtime -$DAYS)" ]; then
            echo "🗑️ Cache for {{.EGET_PROJECT_NAME}} is older than $DAYS days. Cleaning..."
            rm -rf "$DIR"
          fi
          if [ -d "$DIR/.git" ]; then
            cd "$DIR"
            git fetch --tags --quiet
            if ! git rev-parse {{.EGET_VERSION_TAG}} >/dev/null 2>&1; then
              echo -e "\033[31mX\033[0m Error: Tag {{.EGET_VERSION_TAG}} not found in {{.EGET_PROJECT_NAME}}"
              exit 1
            fi
            git reset --hard --quiet
            git clean -fd --quiet
            git checkout {{.EGET_VERSION_TAG}} --quiet
          else
            if ! git clone --depth 1 --branch {{.EGET_VERSION_TAG}} {{.EGET_REPO_URL}} "$DIR" --quiet; then
              echo -e "\033[31mX\033[0m Error: Failed to clone {{.EGET_PROJECT_NAME}}"
              exit 1
            fi
          fi
      - cmd: |
          cd {{.EGET_BUILD_DIR}}/{{.EGET_PROJECT_NAME}}
          goreleaser release --config {{.ROOT}}/templates/goreleaser-main.yaml --snapshot --clean --skip=publish
      - mkdir -p {{.EGET_DIST_DIR}}
      - mv {{.EGET_BUILD_DIR}}/{{.EGET_PROJECT_NAME}}/dist/*.deb {{.EGET_DIST_DIR}}/
      - echo "✅ {{.EGET_PROJECT_NAME}} build complete."

  default:
    cmds:
      - task -l
    silent: true

  latest:
    desc: Check the latest version available on GitHub
    cmds:
      - echo "Latest Version {{.EGET_VERSION_TAG}}"
    silent: true
