---
version: '3'

includes:
  # Register your projects here
  restic: ./projects/restic/Taskfile.yml
  fd: ./projects/fd/Taskfile.yml
  bat: ./projects/bat/Taskfile.yml
  eget: ./projects/eget/Taskfile.yml
  sops: ./projects/sops/Taskfile.yml
  ubi: ./projects/ubi/Taskfile.yml
  fresh: ./projects/fresh/Taskfile.yml
<<<<<<< HEAD
=======
  yazi: ./projects/yazi/Taskfile.yml
>>>>>>> 3faf7a4cdccfbb717557099145a721404801d20f

tasks:
  default:
    desc: List available tasks
    cmds:
      - task -l
    silent: true

  build-all:
    desc: Build DEBS for ALL projects
    cmds:
      - task: restic:build
      - task: fd:build
      - task: bat:build
      - task: eget:build
      - task: sops:build
      - task: ubi:build
      - task: fresh:build
<<<<<<< HEAD
=======
      - task: yazi:build
>>>>>>> 3faf7a4cdccfbb717557099145a721404801d20f
      - echo "🚀 All builds complete! Check dist/ folder."

  clean-all:
    desc: Nuke all build artifacts and caches
    cmds:
      - rm -rf build/ dist/ .cache/
      - echo "✨ Cleaned up workspace."
