---
services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:git-b03fc97-ollama
    container_name: deepseek
    network_mode: host
    restart: always
    env_file:
      - .env
    environment:
      OLLAMA_BASE_URL: http://127.0.0.1:11434
    volumes:
      - ollama:/root/.ollama
      - open-webui:/app/backend/data

volumes:
  ollama:
  open-webui:
