---
version: '3'

env:
  APP_NAME: '{{ .APP_NAME }}'
  USER_NAME: '{{ .USER_NAME | default "username" }}'
  APP_NAME_LOWER: '{{ .APP_NAME | lower }}'

tasks:
  new:
    desc: Create a new lxc app
    preconditions:
      - sh: "command -v minijinja-cli"
        msg: "minijinja-cli is not installed. Please install it to continue."
    cmds:
      - mkdir {{ .APP_NAME_LOWER }}
      - minijinja-cli ./.template/README.md.j2 -D APP_NAME={{ .APP_NAME }} > ./{{ .APP_NAME_LOWER }}/README.md
      - minijinja-cli ./.template/.env.tmpl.j2 -D APP_NAME={{ .APP_NAME }} > ./{{ .APP_NAME_LOWER }}/.env.tmpl
      - minijinja-cli ./.template/update.sh.j2 -D APP_NAME={{ .APP_NAME }} > ./{{ .APP_NAME_LOWER }}/update.sh
      - minijinja-cli ./.template/hooks.json.j2 -D APP_NAME={{ .APP_NAME }} > ./{{ .APP_NAME_LOWER }}/hooks.json
      - minijinja-cli ./.template/webhook.service.j2 -D APP_NAME={{ .APP_NAME }} > ./{{ .APP_NAME_LOWER }}/{{ .APP_NAME_LOWER }}-webhook.service
      - cp ./.template/Taskfile.yml ./{{ .APP_NAME_LOWER }}/Taskfile.yml
  default:
    cmds:
      - task -l
    silent: true
