---
version: '3'

dotenv:
  - .env

tasks:
  export:
    desc: Export the task list
    cmds:
      - task --list > task-list.txt
  deps:
    desc: Install dependencies
    cmds:
      - sudo apt install jq reprepro cron
  sync-check:
    desc: Check and sync released versions of SOPS and Taks
    cmds:
      - ./sync-check.sh

  default:
    cmds:
      - task -l
    silent: true
