---
version: '3'

dotenv:
  - .env

tasks:
  nuke:
    desc: Nuke the packages
    cmds:
      - sudo rm -rf {{.BASE_DIR}}/debian/pool {{.BASE_DIR}}/debian/db {{.BASE_DIR}}/debian/dists
      - sudo rm -rf {{.BASE_DIR}}/ubuntu/pool {{.BASE_DIR}}/ubuntu/db {{.BASE_DIR}}/ubuntu/dists
      - sudo rm -rf {{.BASE_DIR}}/pool {{.BASE_DIR}}/db {{.BASE_DIR}}/dists
  init:
    desc: Initialize the application's environment and configuration files.
    preconditions:
      - test -f .env.tmpl
    cmds:
      - cp .env.tmpl .env
  encrypt:
    desc: Encrypt sensitive configuration files using SOPS.
    preconditions:
      - test -f .env
    cmds:
      - sops -e .env > .env.enc
  decrypt:
    desc: Decrypt sensitive configuration files using SOPS.
    preconditions:
      - test -f .env.enc
    cmds:
      - sops -d --input-type dotenv --output-type dotenv .env.enc > .env
  export:
    silent: true
    desc: Export the task list
    cmds:
      - task --list > task-list.txt
  bootstrap:
    desc: Bootstrap the reprepro environment
    cmds:
      - task: deps
      - task: dirs
      - task: symlinks
  deps:
    desc: Install dependencies
    cmds:
      - >-
        sudo apt install \
          jq reprepro cron dpkg-dev ninja-build gettext cmake curl \
          build-essential git
  sync-check:
    desc: Check and sync released versions of configured apps
    cmds:
      - sudo ./sync-check.sh
  package-apps:
    desc: Check and sync app releases
    cmds:
      - sudo ./package-apps.sh
  package-neovim:
    desc: Package the latest neovim release
    cmds:
      - ./package-neovim.sh
  package-sops:
    desc: Package the latest sops release
    cmds:
      - ./package-sops.sh
  upload-debs:
    desc: Upload the deb packages to a remote server
    cmds:
      - |
        shopt -s nullglob
        DEB_FILES=(*.deb)
        if [ ${#DEB_FILES[@]} -eq 0 ]; then
          echo "No deb files found."
          exit 1
        fi
        echo "Uploading ${#DEB_FILES[@]} file(s)..."
        scp "${DEB_FILES[@]}" {{.REMOTE_USER}}@{{.REMOTE_IP}}:{{.REMOTE_PATH}}
    silent: true
  download:
    desc: Download SOPS and Task .deb files
    cmds:
      - ./download.sh
  clear:
    desc: Remove all packages from all distributions
    cmds:
      - sudo ./clear.sh
  dirs:
    desc: Create reprepro directories
    cmds:
      - sudo mkdir -p {{.BASE_DIR}}/debian/conf
      - sudo mkdir -p {{.BASE_DIR}}/ubuntu/conf
  symlinks:
    desc: Create reprepro symlinks
    cmds:
      - sudo ln -fs $HOME/git/nicholaswilde/homelab/pve/reprepro/debian/conf/distributions {{.BASE_DIR}}/debian/conf/distributions
      - sudo ln -fs $HOME/git/nicholaswilde/homelab/pve/reprepro/ubuntu/conf/distributions {{.BASE_DIR}}/ubuntu/conf/distributions
      # - sudo ln -fs $HOME/git/nicholaswilde/homelab/pve/reprepro/conf/distributions {{.BASE_DIR}}/conf/distributions
      - sudo ln -fs $HOME/git/nicholaswilde/homelab/pve/reprepro/debian/conf/options {{.BASE_DIR}}/debian/conf/options
      - sudo ln -fs $HOME/git/nicholaswilde/homelab/pve/reprepro/ubuntu/conf/options {{.BASE_DIR}}/ubuntu/conf/options
      # - sudo ln -fs $HOME/git/nicholaswilde/homelab/pve/reprepro/conf/options {{.BASE_DIR}}/conf/options
      - sudo ln -fs $HOME/git/nicholaswilde/homelab/pve/reprepro/debian/conf/override.bullseye {{.BASE_DIR}}/debian/conf/override.bullseye
      - sudo ln -fs $HOME/git/nicholaswilde/homelab/pve/reprepro/debian/conf/override.bookworm {{.BASE_DIR}}/debian/conf/override.bookworm
      - sudo ln -fs $HOME/git/nicholaswilde/homelab/pve/reprepro/ubuntu/conf/override.plucky {{.BASE_DIR}}/ubuntu/conf/override.plucky
      - sudo ln -fs $HOME/git/nicholaswilde/homelab/pve/reprepro/ubuntu/conf/override.oracular {{.BASE_DIR}}/ubuntu/conf/override.oracular
      - sudo ln -fs $HOME/git/nicholaswilde/homelab/pve/reprepro/ubuntu/conf/override.noble {{.BASE_DIR}}/ubuntu/conf/override.noble
      - sudo ln -fs $HOME/git/nicholaswilde/homelab/pve/reprepro/ubuntu/conf/override.jammy {{.BASE_DIR}}/ubuntu/conf/override.jammy
  list:
    desc: List all packages in all distributions
    cmds:
      - sudo reprepro -b {{.BASE_DIR}}/debian list bullseye
      - sudo reprepro -b {{.BASE_DIR}}/debian list bookworm
      - sudo reprepro -b {{.BASE_DIR}}/debian list trixie
      - sudo reprepro -b {{.BASE_DIR}}/ubuntu list oracular
      - sudo reprepro -b {{.BASE_DIR}}/ubuntu list noble
      - sudo reprepro -b {{.BASE_DIR}}/ubuntu list jammy
  default:
    cmds:
      - task -l
    silent: true
