version: '3'
dotenv:
  - .env
tasks:
  build-lnav:
    desc: Build lnav
    cmds:
      - sudo ./build-lnav.sh
  nuke:
    desc: Nuke the packages
    cmds:
      - sudo rm -rf {{.BASE_DIR}}/debian/pool {{.BASE_DIR}}/debian/db {{.BASE_DIR}}/debian/dists
      - sudo rm -rf {{.BASE_DIR}}/ubuntu/pool {{.BASE_DIR}}/ubuntu/db {{.BASE_DIR}}/ubuntu/dists
      - sudo rm -rf {{.BASE_DIR}}/raspi/pool {{.BASE_DIR}}/raspi/db {{.BASE_DIR}}/raspi/dists
      - sudo rm -rf {{.BASE_DIR}}/pool {{.BASE_DIR}}/db {{.BASE_DIR}}/dists
  init:
    desc: Initialize the application's environment and configuration files.
    preconditions:
      - test -f .env.tmpl
    cmds:
      - cp .env.tmpl .env
  encrypt:
    desc: Encrypt sensitive configuration files using SOPS.
    cmds:
      - sops -e .env > .env.enc
  decrypt:
    desc: Decrypt sensitive configuration files using SOPS.
    preconditions:
      - test -f .env.enc
    cmds:
      - sops -d --input-type dotenv --output-type dotenv .env.enc > .env
  export:
    silent: true
    desc: Export the task list
    cmds:
      - task --list > task-list.txt
  bootstrap:
    desc: Bootstrap the reprepro environment
    cmds:
      - task: deps
      - task: dirs
      - task: symlinks
  deps-lnav:
    desc: Install lnav dependencies
    cmds:
      - "sudo apt install \\\n  automake\\\n   autoconf \\\n   libunistring-dev \\\
        \n   libpcre2-dev \\\n   libsqlite3-dev \\\n   checkinstall \\\n   zlib1g-dev"
  deps:
    desc: Install dependencies
    cmds:
      - "sudo apt install \\\n  jq reprepro cron dpkg-dev ninja-build gettext cmake\
        \ curl \\\n  build-essential git build-essential cmake libcurl4-openssl-dev\
        \ \\\n  libxml2-dev libssl-dev libxml-security-c-dev pkg-config stow"
  package-lastpass-cli:
    desc: Package the latest lastpass-cli release
    cmds:
      - ./package-lastpass-cli.sh
  package-neovim:
    desc: Package the latest neovim release
    cmds:
      - ./package-neovim.sh
  package-pvetui:
    desc: Package the latest pvetui release
    cmds:
      - ./package-pvetui.sh
  package-sops:
    desc: Package the latest sops release
    cmds:
      - ./package-sops.sh
  upload-debs:
    desc: Upload the deb packages to a remote server
    cmds:
      - "shopt -s nullglob\nDEB_FILES=(*.deb)\nif [ ${#DEB_FILES[@]} -eq 0 ]; then\n\
        \  echo \"No deb files found.\"\n  exit 1\nfi\necho \"Uploading ${#DEB_FILES[@]}\
        \ file(s)...\"\nscp \"${DEB_FILES[@]}\" {{.REMOTE_USER}}@{{.REMOTE_IP}}:{{.REMOTE_PATH}}\n"
    silent: true
  download:
    desc: Download SOPS and Task .deb files
    cmds:
      - ./download.sh
  clear:
    desc: Remove all packages from all distributions
    cmds:
      - sudo ./clear.sh
  dirs:
    desc: Create reprepro directories
    cmds:
      - sudo mkdir -p {{.BASE_DIR}}/debian/conf
      - sudo mkdir -p {{.BASE_DIR}}/ubuntu/conf
      - sudo mkdir -p {{.BASE_DIR}}/raspi/conf
  symlinks:test:
    desc: Create reprepro symlinks
    cmds:
      - sudo stow -n -v -t {{ .BASE_DIR }}/debian debian
      - sudo stow -n -v -t {{ .BASE_DIR }}/ubuntu ubuntu
      - sudo stow -n -v -t {{ .BASE_DIR }}/raspi raspi
  symlinks:
    desc: Create reprepro symlinks
    cmds:
      - sudo stow -v -t {{ .BASE_DIR }}/debian/ debian
      - sudo stow -v -t {{ .BASE_DIR }}/ubuntu/ ubuntu
      - sudo stow -v -t {{ .BASE_DIR }}/raspi/ raspi
  update-reprepro:
    desc: Downloads application tar.gz and .deb files, packages them as needed, and
      adds them to a reprepro repository.
    preconditions:
      - test -f ./update-reprepro.sh
    cmds:
      - sudo ./update-reprepro.sh
  update-raspi:
    desc: Downloads and packages applications for Raspberry Pi 1 / Zero (ARMv6).
    preconditions:
      - test -f ./update-raspi.sh
    cmds:
      - sudo ./update-raspi.sh
  list:
    desc: List all packages in all distributions
    cmds:
      - sudo reprepro -b {{.BASE_DIR}}/debian list bullseye
      - sudo reprepro -b {{.BASE_DIR}}/debian list bookworm
      - sudo reprepro -b {{.BASE_DIR}}/debian list trixie
      - sudo reprepro -b {{.BASE_DIR}}/ubuntu list questing
      - sudo reprepro -b {{.BASE_DIR}}/ubuntu list plucky
      - sudo reprepro -b {{.BASE_DIR}}/ubuntu list oracular
      - sudo reprepro -b {{.BASE_DIR}}/ubuntu list noble
      - sudo reprepro -b {{.BASE_DIR}}/ubuntu list jammy
      - sudo reprepro -b {{.BASE_DIR}}/raspi list trixie
      - sudo reprepro -b {{.BASE_DIR}}/raspi list bookworm
  verify-secrets:
    desc: Checks if the decrypted secret matches the local file
    cmds:
      - echo "Secrets are in sync. Proceeding..."
    preconditions:
      - sh: diff -q .env <(sops -d --input-type dotenv --output-type dotenv .env.enc)
        msg: The encrypted file and unencrypted file do not match! Please re-encrypt
          your changes.
  default:
    cmds:
      - task -l
    silent: true
