---
services:
  app:
    image: nicholaswilde/cheat.sh:sha-139f8c2
    container_name: ${CONTAINER_NAME}
    env_file:
      - .env
    depends_on:
      - redis
    environment:
      - CHEATSH_CACHE_REDIS_HOST=redis
      # - CHEATSH_CACHE_TYPE=none
    ports:
      - "8002:8002"
    volumes:
      - cheatsh_data:/root/.cheat.sh
      - ./etc:/app/etc
    restart: always
  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
volumes:
  redis_data:
  cheatsh_data:
