---
version: '3'

vars:
  VER: '2.5'
  IMAGE: nicholaswilde/mkdocs-material
  PORT: 8000

tasks:
  build:
    desc: Build documentation using Docker and mkdocs-material
    cmds:
      - >-
        docker run --rm -it -v ${PWD}:/docs --platform linux/amd64
        {{ .IMAGE }} build -f ./mkdocs.yml

  update:
    desc: Update docker container
    cmds:
      - docker pull {{ .IMAGE }}
      - docker image prune -a -f
  up:
    desc: Start server
    cmds:
      - task: serve

  serve:
    desc: >-
      Start development server on http://0.0.0.0:{{ .PORT }} using
      Docker and mkdocs-material
    cmds:
      - >-
        docker run --rm -it -p {{ .PORT }}:{{ .PORT}} -v ${PWD}:/docs
        --platform linux/amd64 {{ .IMAGE }} serve
        --dev-addr 0.0.0.0:{{ .PORT }} -f ./mkdocs.yml
    deps:
      - build

  linkcheck:
    desc: Run markdown-link-check
    cmds:
      - ./scripts/linkcheck.sh
    ignore_error: true

  lint:
    desc: Lint the project
    deps:
      - yamllint
      - markdownlint
      - linkcheck
    ignore_error: true

  markdownlint:
    desc: Run markdownlint-cli
    cmds:
      - >-
        docker run --rm -it -v ${PWD}:/markdown:ro
        06kellyjac/markdownlint-cli .
    ignore_error: true

  yamllint:
    desc: Run yamllint
    cmds:
      - >-
        docker run --rm -it -v ${PWD}:${PWD} -w ${PWD}
        programmerassistant/yamllint yamllint .
    ignore_error: true

  gpro:
    desc: Run gemini with gemini-2.5-pro model
    cmds:
      - gemini -m gemini-{{ .VER }}-pro

  gflash:
    desc: Run gemini with flash model
    cmds:
      - gemini -m gemini-{{ .VER }}-flash

  glite:
    desc: Run gemini with lite model
    cmds:
      - gemini -m gemini-{{ .VER }}-lite

  generate-docs-nav:
    desc: Generate MkDocs navigation from content
    cmds:
      - scripts/.venv/bin/python3 scripts/generate_mkdocs_nav.py
    deps:
      - scripts:deps

  default:
    cmds:
      - task -l
    silent: true
