---
version: '3'

includes:
  scripts: ./scripts/Taskfile.yml

vars:
  PORT: 8000

tasks:
  glist:
    desc: List the Gemini models
    cmds:
      - curl -fsSL "https://generativelanguage.googleapis.com/v1beta/models?key=${GEMINI_API_KEY}" | jq -r '.models[].name'
  build:
    desc: Build documentation using zensical
    cmds:
      - uvx zensical build

  up:
    desc: Start server
    cmds:
      - task: serve

  serve:
    desc: >-
      Start development server on http://0.0.0.0:{{ .PORT }} using
      zensical
    cmds:
      - uvx zensical serve --dev-addr 0.0.0.0:{{.PORT}}

  linkcheck:
    desc: Run markdown-link-check
    cmds:
      - ./scripts/linkcheck.sh
    ignore_error: true

  lint:
    desc: Lint the project
    deps:
      - yamllint
      - markdownlint
      - linkcheck
    ignore_error: true

  markdownlint:
    desc: Run markdownlint-cli
    cmds:
      - >-
        docker run --rm -it -v ${PWD}:/markdown:ro
        06kellyjac/markdownlint-cli .
    ignore_error: true

  yamllint:
    desc: Run yamllint
    cmds:
      - >-
        docker run --rm -it -v ${PWD}:${PWD} -w ${PWD}
        programmerassistant/yamllint yamllint .
    ignore_error: true

  gpro:
    desc: Run gemini with gemini-2.5-pro model
    cmds:
      - gemini -m gemini-{{ .VER }}-pro

  gflash:
    desc: Run gemini with flash model
    cmds:
      - gemini -m gemini-{{ .VER }}-flash

  glite:
    desc: Run gemini with lite model
    cmds:
      - gemini -m gemini-{{ .VER }}-lite

  generate-docs-nav:
    desc: Generate MkDocs navigation from content
    cmds:
      - uv run python scripts/generate_mkdocs_nav.py
  docs:deps:
    desc: Install Zensical
    cmds:
      - uv pip install zensical

  docs:check:
    desc: Check Zensical version
    cmds:
      - uv pip show zensical
  docs:update:
    desc: Update Zensical
    cmds:
      - uv pip install --upgrade zensical

  encrypt:
    desc: Encrypt secrets
    cmds:
      - >-
        sops -e --input-type json --output-type json
        .gemini/settings.json > .gemini/settings.json.enc

  decrypt:
    desc: Decrypt secrets
    cmds:
      - >-
        sops -d --input-type json --output-type json
        .gemini/settings.json.enc > .gemini/settings.json

  default:
    cmds:
      - task -l
    silent: true
