[project]
site_name = "Homelab"
site_description = "My notes on various things"
site_author = "Nicholas Wilde"
site_url = "https://nicholaswilde.io/homelab"
copyright = "Copyright &copy; 2025 Nicholas Wilde"
dev_addr = "0.0.0.0:8000"
repo_name = "nicholaswilde/homelab"
repo_url = "https://github.com/nicholaswilde/homelab"
edit_uri = "edit/main/docs/"
extra_css = [
  "stylesheets/extra.css",
]

[[project.nav]]
Home = "index.md"

[[project.nav]]
About = [
  { "Development" = "about/development.md" },
  { "Future" = "about/future.md" },
]

[[project.nav]]
Apps = [
  { "Adguard Home Sync" = "apps/adguardhome-sync.md" },
  { "AdGuard Home" = "apps/adguardhome.md" },
  { "Apt-Cacher NG" = "apps/aptcacherng.md" },
  { "aria2" = "apps/aria2.md" },
  { "authentik" = "apps/authentik.md" },
  { "Beszel" = "apps/beszel.md" },
  { "BentoPDF" = "apps/bentopdf.md" },
  { "ChangeDetection" = "apps/changedetection.md" },
  { "ConvertX" = "apps/convertx.md" },
  { "CyberKeyGen" = "apps/cyberkeygen.md" },
  { "Excalidraw" = "apps/excalidraw.md" },
  { "FrameFi" = "apps/frame-fi.md" },
  { "Gatus" = "apps/gatus.md" },
  { "File Browser" = "apps/filebrowser.md" },
  { "Gitea" = "apps/gitea.md" },
  { "Homebox" = "apps/homebox.md" },
  { "Home Assistant" = "apps/home-assistant.md" },
  { "homepage" = "apps/homepage.md" },
  { "Immich" = "apps/immich.md" },
  { "Immich-Go" = "apps/immich-go.md" },
  { "Installer" = "apps/installer.md" },
  { "IT-TOOLS" = "apps/it-tools.md" },
  { "LocalSend" = "apps/localsend.md" },
  { "LogWard" = "apps/logward.md" },
  { "mailrise" = "apps/mailrise.md" },
  { "MCP Server" = "apps/mcp-server.md" },
  { "MySpeed" = "apps/myspeed.md" },
  { "netboot.xyz" = "apps/netbootxyz.md" },
  { "OpenMediaVault" = "apps/openmediavault.md" },
  { "PatchMon" = "apps/patchmon.md" },
  { "Pinchflat" = "apps/pinchflat.md" },
  { "Proxmox" = "apps/proxmox.md" },
  { "qBittorrent" = "apps/qbittorrent.md" },
  { "Reactive Resume" = "apps/reactive-resume.md" },
  { "Registry" = "apps/registry.md" },
  { "reprepro" = "apps/reprepro.md" },
  { "Stirling PDF" = "apps/stirling-pdf.md" },
  { "Traefik" = "apps/traefik.md" },
  { "Unbound" = "apps/unbound.md" },
  { "Wallos" = "apps/wallos.md" },
  { "Vaultwarden" = "apps/vaultwarden.md" },
  { "Vaultwarden Backup" = "apps/vaultwarden-backup.md" },
  { "Ventoy" = "apps/ventoy.md" },
  { "webhook" = "apps/webhook.md" },
  { "WatchYourLAN" = "apps/watchyourlan.md" },
  { "Windows 11" = "apps/w11.md" },
  { "Change Detection" = "apps/changedetection.md" },
  { "vaultwarden-backup" = "apps/vaultwarden-backup.md" },
]

[[project.nav]]
Hardware = [
  { "Apple TV" = "hardware/apple-tv.md" },
  { "ASUS Chromebook Plus CX34" = "hardware/asus-chromebook-plus-cx34.md" },
  { "Chromecast" = "hardware/chromecast.md" },
  { "Digital Picture Frame" = "hardware/digital-picture-frame.md" },
  { "HP Pro desk 600 G3 SFF" = "hardware/hp-prodesk-600-g3-sff.md" },
  { "Intel NUC" = "hardware/nuc.md" },
  { "Lenovo Chromebook Flex 5" = "hardware/lenovo-chromebook-flex-5.md" },
  { "LG Appliances" = "hardware/lg-appliances.md" },
  { "LilyGo T-Dongle S3" = "hardware/lilygo-t-dongle-s3.md" },
  { "Raspberry Pi 1 Model B+" = "hardware/rpi1.md" },
  { "Raspberry Pi 2" = "hardware/rpi2.md" },
  { "Raspberry Pi 4 8GB" = "hardware/rpi4.md" },
  { "Raspberry Pi 5 16GB" = "hardware/rpi5.md" },
  { "Raspberry Pi Zero W" = "hardware/rpi0.md" },
  { "Roborock" = "hardware/roborock.md" },
  { "UniFi" = "hardware/unifi.md" },
  { "Wyze Cam" = "hardware/wyze-cam.md" },
]

[[project.nav]]
"Operating Systems" = [
  { "Chrome OS" = "os/chromeos.md" },
  { "DietPi" = "os/dietpi.md" },
  { "Raspberry Pi OS" = "os/rpios.md" },
]

[[project.nav]]
Tools = [
  { "Apprise" = "tools/apprise.md" },
  { "Autofs" = "tools/autofs.md" },
  { "bat" = "tools/bat.md" },
  { "cheat" = "tools/cheat.md" },
  { "docker-volume-backup" = "tools/docker-volume-backup.md" },
  { "duf" = "tools/duf.md" },
  { ".env Files" = "tools/env-files.md" },
  { "eza" = "tools/eza.md" },
  { "fd" = "tools/fd.md" },
  { "fzf" = "tools/fzf.md" },
  { "Gemini CLI Commands" = "tools/gemini-commands.md" },
  { "Google Gemini CLI" = "tools/google-gemini-cli.md" },
  { "Google Jules" = "tools/google-jules.md" },
  { "jinja2-cli" = "tools/jinja2-cli.md" },
  { "LVM" = "tools/lvm.md" },
  { "LocalSend Go" = "tools/localsend-go.md" },
  { "micro" = "tools/micro.md" },
  { "pass" = "tools/pass.md" },
  { "rclone" = "tools/rclone.md" },
  { "restic" = "tools/restic.md" },
  { "ripgrep" = "tools/ripgrep.md" },
  { "sd" = "tools/sd.md" },
  { "SOPS" = "tools/sops.md" },
  { "Syncthing" = "tools/syncthing.md" },
  { "Task" = "tools/task.md" },
  { "tmux" = "tools/tmux.md" },
  { "LocalSend" = "tools/localsend.md" },
]

[[project.nav]]
Travel = "travel.md"

[[project.nav]]
Reference = [
  { "Cheatsheet" = "reference/cheatsheet.md" },
  { "Emoji" = "reference/emoji.md" },
  { "Tags" = "reference/tags.md" },
]

[project.extra]
social = [
    { icon = "fontawesome/solid/house", link = "https://nicholaswilde.io/" },
    { icon = "fontawesome/brands/github", link = "https://github.com/nicholaswilde" },
    { icon = "fontawesome/brands/twitter", link = "https://twitter.com/nicholascwilde" },
    { icon = "fontawesome/brands/instagram", link = "https://www.instagram.com/wildewoodworking/" },
    { icon = "fontawesome/brands/linkedin-in", link = "https://www.linkedin.com/in/nicholaswilde" },
    { icon = "fontawesome/brands/facebook", link = "https://www.facebook.com/nicholas.wilde/" },
    { icon = "fontawesome/brands/keybase", link = "https://keybase.io/nicholaswilde" },
    { icon = "fontawesome/solid/key", link = "https://github.com/nicholaswilde.gpg" },
]

[project.theme]
name = "material"
features = [
    "content.code.copy",
    "content.code.select",
    "content.code.annotate",
    "content.tabs.link",
]

[[project.theme.palette]]
media = "(prefers-color-scheme)"
toggle = { icon = "material/brightness-auto", name = "Switch to light mode" }

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle = { icon = "material/brightness-7", name = "Switch to dark mode" }

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle = { icon = "material/brightness-4", name = "Switch to system preference" }

[project.plugins]
search = {}
tags = {}
minify = { minify_html = true }

[project.markdown_extensions]
[project.markdown_extensions.admonition]
[project.markdown_extensions.abbr]
[project.markdown_extensions.attr_list]
[project.markdown_extensions.def_list]
[project.markdown_extensions.footnotes]
[project.markdown_extensions.meta]
[project.markdown_extensions.tables]
[project.markdown_extensions.md_in_html]

[project.markdown_extensions.toc]
permalink = true

[project.markdown_extensions.pymdownx]

[project.markdown_extensions.pymdownx.arithmatex]
generic = true

[project.markdown_extensions.pymdownx.betterem]
smart_enable = "all"

[project.markdown_extensions.pymdownx.caret]
[project.markdown_extensions.pymdownx.critic]
[project.markdown_extensions.pymdownx.details]

[project.markdown_extensions.pymdownx.emoji]
emoji_index = "zensical.extensions.emoji.twemoji"
emoji_generator = "zensical.extensions.emoji.to_svg"

[project.markdown_extensions.pymdownx.highlight]
anchor_linenums = true
line_spans = "__span"
pygments_lang_class = true

[project.markdown_extensions.pymdownx.inlinehilite]
[project.markdown_extensions.pymdownx.keys]

[project.markdown_extensions.pymdownx.magiclink]
repo_url_shorthand = true
user = "nicholaswilde"
repo = "homepage"

[project.markdown_extensions.pymdownx.mark]

[project.markdown_extensions.pymdownx.snippets]
base_path = [ "./pve", "./docker", "./vm", "./docs", "./lxc", "./tools" ]

[project.markdown_extensions.pymdownx.smartsymbols]

[project.markdown_extensions.pymdownx.superfences]
custom_fences = [ { name = "mermaid", class = "mermaid", format = "pymdownx.superfences.fence_code_format" } ]

[project.markdown_extensions.pymdownx.tabbed]
alternate_style = true

[project.markdown_extensions.pymdownx.tasklist]
custom_checkbox = true

[project.markdown_extensions.pymdownx.tilde]
