---
version: '3'

dotenv:
  - .env

tasks:
  create-template:
    desc: Create template from existing .env file
    preconditions:
      - test -f .env
    cmds:
      - "sed '/^ *#/! s/=.*/=/' .env > .env.tmpl"
  install-service:
    desc: Install the application's systemd service.
    preconditions:
      - test -f ./webhook.service
    cmds:
      - "sudo cp ./webhook.service /etc/systemd/system/"
      - task: enable
  reload:
    desc: Reload the application's systemd service.
    cmds:
      - sudo systemctl daemon-reload
  enable:
    desc: Enable the application's systemd service.
    cmds:
      - sudo systemctl enable {{ .SERVICE_NAME }}.service
  decrypt:
    desc: Decrypt sensitive configuration files using SOPS.
    preconditions:
      - test -f .env.enc
    cmds:
      - sops -d --input-type dotenv --output-type dotenv .env.enc > .env
  enable:
    desc: Enable the application's systemd service.
    cmds:
      - systemctl enable {{ .SERVICE_NAME }}.service
  encrypt:
    desc: Encrypt sensitive configuration files using SOPS.
    preconditions:
      - test -f .env
    cmds:
      - sops -e .env > .env.enc
  export:
    silent: true
    desc: Export the task list to `task-list.txt`.
    cmds:
      - task --list > task-list.txt
  init:
    desc: Initialize the application's environment and configuration files.
    preconditions:
      - test -f .env.tmpl
    cmds:
      - cp .env.tmpl .env
  mklinks:
    desc: Create symbolic links for configuration files.
    preconditions:
      - test -d {{ .CONFIG_DIR }}
    cmds:
      - ln -sf {{ .TASKFILE_DIR }}/daemon.json  {{ .CONFIG_DIR }}/daemon.json
  restart:
    desc: Restart the application's systemd service.
    cmds:
      - systemctl restart {{ .SERVICE_NAME }}.service
  start:
    desc: Start the application's systemd service.
    cmds:
      - systemctl start {{ .SERVICE_NAME }}.service
  status:
    desc: Check the status of the application's systemd service.
    cmds:
      - systemctl status {{ .SERVICE_NAME }}.service
  stop:
    desc: Stop the application's systemd service.
    cmds:
      - systemctl stop {{ .SERVICE_NAME }}.service
  update:
    desc: Update the application or its running containers.
    preconditions:
      - test -f update.sh
    cmds:
      - ./update.sh
  upgrade:
    desc: Upgrade the application by pulling the latest changes and updating.
    cmds:
      - git pull origin
      - task: update
  verify-secrets:
    desc: Checks if the decrypted secret matches the local file
    cmds:
      - echo "Secrets are in sync. Proceeding..."
    preconditions:
      - sh: diff -q .env <(sops -d --input-type dotenv --output-type dotenv .env.enc)
        msg: "The encrypted file and unencrypted file do not match! Please re-encrypt your changes."
  watch:
    desc: Watch the logs
    cmds:
      - journalctl -f -t reprepro-updater
  follow:
    desc: Follow the logs
    cmds:
      - task: watch
  default:
    cmds:
      - task -l
    silent: true
    desc: List all available tasks.
