---
services:
  registry:
    container_name: registry
    image: library/registry:3.0.0
    environment:
      - REGISTRY_STORAGE_DELETE_ENABLED=true
      - REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/var/lib/registry
      - REGISTRY_PROXY_REMOTEURL="https://registry-1.docker.io"
      - REGISTRY_PROXY_USERNAME=$DOCKER_USER
      - REGISTRY_PROXY_PASSWORD=$DOCKER_TOKEN
    env_file:
      - .env
    ports:
      - '5000:5000'
    volumes:
      - ${REGISTRY_DIR:-/var/lib/registry}:/var/lib/registry
    restart: always
