---
configs:
  email:
    urls:
      - !env_var EMAIL_URL
    mailrise:
      title_template: "${subject}"
      body_template: "${body}"
      body_format: text

# smtp:
#   auth:
#     basic:
#       username: password
