---
configs:
  email:
    urls:
      - !env_var EMAIL_URL
    mailrise:
      title_template: "${subject}"
      body_template: "${body}"
      body_format: text
  ntfy:
    urls:
      - !env_var NTFY_URL
    mailrise:
      title_template: "${subject}"
      body_template: "${body}"
      body_format: text
  gotify:
    urls:
      - !env_var GOTIFY_URL
    mailrise:
      title_template: "${subject}"
      body_template: "${body}"
      body_format: text
  all:
    urls:
      - !env_var EMAIL_URL
      - !env_var NTFY_URL
      - !env_var GOTIFY_URL
    mailrise:
      title_template: "${subject}"
      body_template: "${body}"
      body_format: text

# smtp:
#   auth:
#     basic:
#       username: password
