---
version: '3'

includes:
  lib:
    taskfile: ../Taskfile.yml
    flatten: true

tasks:
  # update-d:
  #   desc: Update running containers
  #   dir: .
  #   cmds:
  #     - task -t ../Taskfile.yml update-d
  #     # - docker compose up --force-recreate --build -d
  #     # - docker image prune -a -f

  update:
    desc: Update running containers
    cmds:
      - docker compose up --force-recreate --build
      - docker image prune -a -f
  up:
    desc: Docker Up
    cmds:
      - docker compose up
  upgrade:
    desc: upgrade
    cmds:
      - git pull origin
      - task: update
  upgrade-d:
    desc: upgrade
    cmds:
      - git pull origin
      - task: update
  default:
    cmds:
      - task -l
    silent: true
