---
version: '3'

dotenv:
  - .env

tasks:
  export:
    desc: Export the task list
    cmds:
      - task --list > task-list.txt
  test-remote:
    desc: Send a test email to remote address
    cmds:
      - 'swaks --to email@mailrise.xyz --server smtp.l.nicholaswilde.io:8025 --body "this is the body" --header "Subject: subject"'
  test:
    desc: Send a test email
    cmds:
      - "swaks --to email@mailrise.xyz --server localhost --port 8025"
  status:
    desc: Status
    cmds:
      - systemctl status {{ .SERVICE_NAME }}.service
  init:
    desc: Init
    cmds:
      - cp .env.tmpl .env
  decrypt:
    desc: Decrypt .env using SOPS
    cmds:
      - sops -d --input-type dotenv --output-type dotenv .env.enc > .env
  encrypt:
    desc: Encrypt .env using SOPS
    cmds:
      - sops -e .env > .env.enc
  update:
    desc: Update running containers
    cmds:
      - docker compose up --force-recreate --build -d
      - docker image prune -a -f
  up:
    desc: Tun Docker compose in the foreground.
    cmds:
      - docker compose up
  up-d:
    desc: Run Docker compose in the background.
    cmds:
      - docker compose up -d --remove-orphans
  restart:
    desc: Restart Docker containers
    cmds:
      - "docker compose restart"
  upgrade:
    desc: Upgrade running containers
    cmds:
      - git pull origin
      - task: update
  stop:
    desc: Stop registry container
    cmds:
      - docker compose stop
  mklinks:
    desc: Make client symlinks
    cmds:
      - ln -sf {{ .TASKFILE_DIR }}/mailrise.conf  {{ .CONFIG_DIR }}/mailrise.conf
  default:
    cmds:
      - task -l
    silent: true
