---
version: '3'

dotenv:
  - .env

tasks:
  export:
    silent: true
    desc: Export the task list
    cmds:
      - task --list > task-list.txt
  enable:
    desc: Enable service
    cmds:
      - systemctl enable {{ .SERVICE_NAME }}.service
      - systemctl enable {{ .SERVICE_NAME2 }}.service
  status:
    desc: Service status
    cmds:
      - systemctl status {{ .SERVICE_NAME }}.service
      - systemctl status {{ .SERVICE_NAME2 }}.service
  init:
    desc: Init
    preconditions:
      - test -f .env.tmpl
    cmds:
      - cp .env.tmpl .env
  decrypt:
    desc: Decrypt .env using SOPS
    preconditions:
      - test -f .env.enc
      - test -f rpc.secret.enc
      - test -f aria2.daemon.enc
    cmds:
      - sops -d --input-type dotenv --output-type dotenv .env.enc > .env
      - sops -d --input-type yaml --output-type yaml rpc.secret.enc > rpc.secret
      - sops -d --input-type dotenv --output-type dotenv aria2.daemon.enc > aria2.daemon
  encrypt:
    desc: Encrypt .env using SOPS
    preconditions:
      - test -f .env
      - test -f rpc.secret
      - test -f aria2.daemon
    cmds:
      - sops -e --input-type dotenv --output-type dotenv .env > .env.enc
      - sops -e --input-type yaml --output-type yaml rpc.secret > rpc.secret.enc
      - sops -e --input-type dotenv --output-type dotenv aria2.daemon > aria2.daemon.enc
  update:
    desc: Update running containers
    preconditions:
      - test -f update.sh
    cmds:
      - ./update.sh
  restart:
    desc: Resart service
    cmds:
      - systemctl restart {{ .SERVICE_NAME }}.service
      - systemctl restart {{ .SERVICE_NAME2 }}.service
  upgrade:
    desc: Upgrade app
    cmds:
      - git pull origin
      - task: update
  stop:
    desc: Stop service
    cmds:
      - systemctl stop {{ .SERVICE_NAME }}.service
      - systemctl stop {{ .SERVICE_NAME2 }}.service
  start:
    desc: Start service
    cmds:
      - systemctl start {{ .SERVICE_NAME }}.service
      - systemctl start {{ .SERVICE_NAME2 }}.service
  mklinks:
    desc: Make client symlinks
    preconditions:
      - test -f {{ .TASKFILE_DIR }}/aria2.daemon
      - test -d {{ .CONFIG_DIR }}
      - test -f {{ .TASKFILE_DIR }}/nginx/ariang.conf
    cmds:
      - ln -sf {{ .TASKFILE_DIR }}/aria2.daemon {{ .CONFIG_DIR }}/aria2.daemon
      - stow --adopt -v -t /etc/nginx {{ .TASKFILE_DIR }}/nginx/
  default:
    cmds:
      - task -l
    silent: true
