---
http:
 #region routers 
  routers:
    apache-guacamole:
      entryPoints:
        - "websecure"
      rule: "Host(`guac.l.nicholaswilde.io`)"
      middlewares:
        - guacamole-add-prefix
        - default-headers@file
        - https-redirectscheme@file
      tls: {}
      service: apache-guacamole
#endregion
#region services
  services:
    apache-guacamole:
      loadBalancer:
        servers:
          - url: "http://192.168.2.156:8080"
        passHostHeader: true
#endregion
  middlewares:
    guacamole-add-prefix:
      addprefix:
        prefix: "/guacamole"
