---
http:
 #region routers 
  routers:
    aria2:
      entryPoints:
        - "websecure"
      rule: "Host(`aria2.l.nicholaswilde.io`)"
      middlewares:
        - default-headers@file
        - https-redirectscheme@file
      tls: {}
      service: aria2
    aria2s:
      entryPoints:
        - "websecure"
      rule: "Host(`aria2s.l.nicholaswilde.io`)"
      middlewares:
        - default-headers@file
        - https-redirectscheme@file
      tls: {}
      service: aria2s
#endregion
#region services
  services:
    aria2:
      loadBalancer:
        servers:
          - url: "http://192.168.2.21:6880"
        passHostHeader: true
    aria2s:
      loadBalancer:
        servers:
          - url: "http://192.168.2.21:6800"
        passHostHeader: true
#endregion
