---
http:
 #region routers 
  routers:
    cheatsh:
      entryPoints:
        - "websecure"
      rule: "Host(`cheatsh.l.nicholaswilde.io`)"
      middlewares:
        - default-headers@file
        - https-redirectscheme@file
      tls: {}
      service: cheatsh
#endregion
#region services
  services:
    cheatsh:
      loadBalancer:
        servers:
          - url: "http://192.168.2.103:8002"
        passHostHeader: true
#endregion
