---
http:
 #region routers 
  routers:
    chronograph:
      entryPoints:
        - "websecure"
      rule: "Host(`chronograph.l.nicholaswilde.io`)"
      middlewares:
        - default-headers@file
        - https-redirectscheme@file
      tls: {}
      service: chronograph
  
#endregion
#region services
  services:
    chronograph:
      loadBalancer:
        servers:
          - url: "http://192.168.1.109:8888"
        passHostHeader: true
#endregion
