---
http:
 #region routers 
  routers:
    deepseek:
      entryPoints:
        - "websecure"
      rule: "Host(`deepseek.l.nicholaswilde.io`)"
      middlewares:
        - default-headers@file
        - https-redirectscheme@file
      tls: {}
      service: deepseek
#endregion
#region services
  services:
    deepseek:
      loadBalancer:
        servers:
          - url: "http://192.168.2.94:8080"
        passHostHeader: true
#endregion
