---
http:
 #region routers 
  routers:
    it-tools:
      entryPoints:
        - "websecure"
      rule: "Host(`it-tools.l.nicholaswilde.io`)"
      middlewares:
        - default-headers@file
        - https-redirectscheme@file
      tls: {}
      service: it-tools
#endregion
#region services
  services:
    it-tools:
      loadBalancer:
        servers:
          - url: "http://192.168.2.52:8080"
        passHostHeader: true
#endregion
