---
http:
 #region routers 
  routers:
    kestra:
      entryPoints:
        - "websecure"
      rule: "Host(`kestra.l.nicholaswilde.io`)"
      middlewares:
        - default-headers@file
        - https-redirectscheme@file
      tls: {}
      service: kestra
#endregion
#region services
  services:
    kestra:
      loadBalancer:
        servers:
          - url: "http://192.168.2.93:8080"
        passHostHeader: true
#endregion
