# ---
# tcp:
 # #region routers
  # routers:
    # mailrise:
      # entryPoints:
        # - "mailsecure"
      # rule: "HostSNI(`smtp.l.nicholaswilde.io`)"
      # service: mailrise
      # tls:
        # passthrough: true
# #endregion
# #region services
  # services:
    # mailrise:
      # loadBalancer:
        # servers:
          # - address: "192.168.1.62:8025"
# #endregion
