---
http:
 #region routers 
  routers:
    myspeed:
      entryPoints:
        - "websecure"
      rule: "Host(`myspeed.l.nicholaswilde.io`)"
      middlewares:
        - default-headers@file
        - https-redirectscheme@file
      tls: {}
      service: myspeed
  
#endregion
#region services
  services:
    myspeed:
      loadBalancer:
        servers:
          - url: "http://192.168.2.136:5216"
        passHostHeader: true
# #endregion
