---
http:
 #region routers 
  routers:
    nodered:
      entryPoints:
        - "websecure"
      rule: "Host(`nodered.l.nicholaswilde.io`)"
      middlewares:
        - default-headers@file
        - https-redirectscheme@file
      tls: {}
      service: nodered
  
#endregion
#region services
  services:
    nodered:
      loadBalancer:
        servers:
          - url: "http://192.168.1.143:1880"
        passHostHeader: true
#endregion
