---
http:
 #region routers 
  routers:
    ntfy:
      entryPoints:
        - "websecure"
      rule: "Host(`ntfy.l.nicholaswilde.io`)"
      middlewares:
        - default-headers@file
        - https-redirectscheme@file
      tls: {}
      service: ntfy
#endregion
#region services
  services:
    ntfy:
      loadBalancer:
        servers:
          - url: "http://192.168.2.160"
        passHostHeader: true
#endregion
