---
http:
 #region routers 
  routers:
    portainer:
      entryPoints:
        - "websecure"
      rule: "Host(`portainer.l.nicholaswilde.io`)"
      middlewares:
        - default-headers@file
        - https-redirectscheme@file
      tls: {}
      service: portainer
  
#endregion
#region services
  services:
    portainer:
      loadBalancer:
        servers:
          - url: "https://192.168.1.143:9443"
        passHostHeader: true
#endregion
