---
http:
 #region routers 
  routers:
    proxmox01:
      entryPoints:
        - "websecure"
      rule: "Host(`pve01.l.nicholaswilde.io`)"
      middlewares:
        - default-headers@file
        - https-redirectscheme@file
      tls: {}
      service: proxmox01
    proxmox03:
      entryPoints:
        - "websecure"
      rule: "Host(`pve03.l.nicholaswilde.io`)"
      middlewares:
        - default-headers@file
        - https-redirectscheme@file
      tls: {}
      service: proxmox03
    proxmox04:
      entryPoints:
        - "websecure"
      rule: "Host(`pve04.l.nicholaswilde.io`)"
      middlewares:
        - default-headers@file
        - https-redirectscheme@file
      tls: {}
      service: proxmox04
  
#endregion
#region services
  services:
    proxmox01:
      loadBalancer:
        servers:
          - url: "https://192.168.1.128:8006"
        passHostHeader: true
    proxmox03:
      loadBalancer:
        servers:
          - url: "https://192.168.1.141:8006"
        passHostHeader: true
    proxmox04:
      loadBalancer:
        servers:
          - url: "https://192.168.1.66:8006"
        passHostHeader: true


#endregion
