---
http:
 #region routers 
  routers:
    semaphore:
      entryPoints:
        - "websecure"
      rule: "Host(`semaphore.l.nicholaswilde.io`)"
      middlewares:
        - default-headers@file
        - https-redirectscheme@file
      tls: {}
      service: semaphore
#endregion
#region services
  services:
    semaphore:
      loadBalancer:
        servers:
          - url: "http://192.168.2.90:3000"
        passHostHeader: true
#endregion
