---
http:
 #region routers 
  routers:
    shlink:
      entryPoints:
        - "websecure"
      rule: "Host(`sh.rt`)"
      middlewares:
        - default-headers@file
        - https-redirectscheme@file
      tls: {}
      service: shlink
    shlink2:
      entryPoints:
        - "websecure"
      rule: "Host(`shlink.l.nicholaswilde.io`)"
      middlewares:
        - default-headers@file
        - https-redirectscheme@file
      tls: {}
      service: shlink2
#endregion
#region services
  services:
    shlink:
      loadBalancer:
        servers:
          - url: "http://192.168.2.92:8080"
        passHostHeader: true
    shlink2:
      loadBalancer:
        servers:
          - url: "http://192.168.2.92:8081"
        passHostHeader: true

#endregion
  middlewares:
    https-redirectscheme:
      redirectScheme:
        scheme: https
        permanent: true
    default-headers:
      headers:
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https

    default-whitelist:
      ipAllowList:
        sourceRange:
        - "10.0.0.0/8"
        - "192.168.0.0/16"
        - "172.16.0.0/12"

    secured:
      chain:
        middlewares:
        - default-whitelist
        - default-headers
