---
http:
 #region routers 
  routers:
    uptimekuma:
      entryPoints:
        - "websecure"
      rule: "Host(`up.l.nicholaswilde.io`)"
      middlewares:
        - default-headers@file
        - https-redirectscheme@file
      tls: {}
      service: uptimekuma
  
#endregion
#region services
  services:
    uptimekuma:
      loadBalancer:
        servers:
          - url: "http://192.168.1.143:3001"
        passHostHeader: true
#endregion
