---
http:
 #region routers 
  routers:
    ventoy:
      entryPoints:
        - "websecure"
      rule: "Host(`ventoy.l.nicholaswilde.io`)"
      middlewares:
        - default-headers@file
        - https-redirectscheme@file
      tls: {}
      service: ventoy
#endregion
#region services
  services:
    ventoy:
      loadBalancer:
        servers:
          - url: "http://192.168.2.70:24680"
        passHostHeader: true
#endregion
