---
http:
 #region routers 
  routers:
    watchyourlan:
      entryPoints:
        - "websecure"
      rule: "Host(`watch.l.nicholaswilde.io`)"
      middlewares:
        - default-headers@file
        - https-redirectscheme@file
      tls: {}
      service: watchyourlan
#endregion
#region services
  services:
    watchyourlan:
      loadBalancer:
        servers:
          - url: "http://192.168.2.53:8840"
        passHostHeader: true
