---
version: '3'

dotenv:
  - .env

tasks:
  creds:
    desc: Show credentials
    cmds:
      - cat ~/semaphore.creds
  init:
    desc: Init
    cmds:
      - cp .env.tmpl .env
      - cp config.json.tmpl config.json
  decrypt:
    desc: Decrypt files using SOPS
    cmds:
      - sops -d --input-type dotenv --output-type dotenv .env.enc > .env
      - sops -d --input-type json --output-type json config.json.enc > config.json
      - sops -d semaphore_db.bolt.enc > semaphore_db.bolt
  encrypt:
    desc: Encrypt files using SOPS
    cmds:
      - sops -e .env > .env.enc
      - sops -e config.json > config.json.enc
      - sops -e semaphore_db.bolt >  semaphore_db.bolt.enc
  default:
    cmds:
      - task -l
    silent: true
