---
version: '3'

dotenv:
  - .env

tasks:
  update:
    desc: Update Semaphore
    cmds:
     - ./update.sh
  export:
    desc: Export the task list
    cmds:
      - task --list > task-list.txt
  backup:
    desc: Backup files
    cmds:
      - cp {{ .INSTALL_DIR }}/config.json {{ .INSTALL_DIR }}/config.json.bak 
      - cp {{ .INSTALL_DIR }}/semaphore_db.bolt {{ .INSTALL_DIR }}/semaphore_db.bolt.bak
  copy:
    desc: Copy config files from install dir to repo
    cmds:
      - cp {{ .INSTALL_DIR }}/config.json {{ .TASKFILE_DIR }}/config.json 
      - cp {{ .INSTALL_DIR }}/semaphore_db.bolt {{ .TASKFILE_DIR }}/semaphore_db.bolt
  mklinks:
    desc: Make symlinks
    cmds:
      - ln -sf {{ .TASKFILE_DIR }}/config.json  {{ .INSTALL_DIR }}/config.json
      - ln -sf {{ .TASKFILE_DIR }}/semaphore_db.bolt {{ .INSTALL_DIR }}/semaphore_db.bolt
  restart:
    desc: Restart service
    cmds:
      - systemctl restart {{ .SERVICE_NAME }}.service
  start:
    desc: Start service
    cmds:
      - systemctl start {{ .SERVICE_NAME }}.service
  stop:
    desc: Stop service
    cmds:
      - systemctl stop {{ .SERVICE_NAME }}.service
  creds:
    desc: Show credentials
    cmds:
      - cat ~/semaphore.creds
  init:
    desc: Init
    cmds:
      - cp .env.tmpl .env
      - cp config.json.tmpl config.json
  decrypt:
    desc: Decrypt files using SOPS
    cmds:
      - sops -d --input-type dotenv --output-type dotenv .env.enc > .env
      - sops -d --input-type json --output-type json config.json.enc > config.json
      - sops -d semaphore_db.bolt.enc > semaphore_db.bolt
  encrypt:
    desc: Encrypt files using SOPS
    cmds:
      - sops -e .env > .env.enc
      - sops -e config.json > config.json.enc
      - sops -e semaphore_db.bolt >  semaphore_db.bolt.enc
  default:
    cmds:
      - task -l
    silent: true
