---
version: '3'

dotenv:
  - .env

tasks:
  export:
    silent: true
    desc: Export the task list
    cmds:
      - task --list > task-list.txt
  start:
    desc: Start service
    cmds:
      - systemctl start {{ .SERVICE_NAME }}.service
  stop:
    desc: Stop service
    cmds:
      - systemctl stop {{ .SERVICE_NAME }}.service
  restart:
    desc: Restart service
    cmds:
      - systemctl restart {{ .SERVICE_NAME }}.service
  init:
    desc: Init
    cmds:
      - cp .env.tmpl .env
  # Currently not working
  mklinks:
    desc: Make symlinks
    cmds:
      - ln -s {{ .TASKFILE_DIR }}/acng.conf /etc/apt-cacher-ng/
  watch:
    desc: Watch the logs
    cmds:
      - tail -f /var/log/apt-cacher-ng/apt-cacher.log
  follow:
    desc: Follow the logs
    cmds:
      - task: watch
  default:
    cmds:
      - task -l
    silent: true
