version: '3'
dotenv:
  - .env
tasks:
  export:
    silent: true
    desc: Export the task list
    cmds:
      - task --list > task-list.txt
  status:
    desc: Status
    cmds:
      - systemctl status {{ .SERVICE_NAME }}.service
  init:
    desc: Init
    cmds:
      - cp .env.tmpl .env
  decrypt:
    desc: Decrypt .env using SOPS
    cmds:
      - sops -d --input-type dotenv --output-type dotenv .env.enc > .env
  encrypt:
    desc: Encrypt .env using SOPS
    cmds:
      - sops -e .env > .env.enc
  update:
    desc: Update Wallos
    cmds:
      - bash -c /usr/bin/update
  upgrade:
    desc: Upgrade Wallos
    cmds:
      - git pull origin
      - task: update
  verify-secrets:
    desc: Checks if the decrypted secret matches the local file
    cmds:
      - echo "Secrets are in sync. Proceeding..."
    preconditions:
      - sh: diff -q .env <(sops -d --input-type dotenv --output-type dotenv .env.enc)
        msg: The encrypted file and unencrypted file do not match! Please re-encrypt
          your changes.
  mklinks:
    desc: Make client symlinks
    cmds:
      - ln -sf {{ .TASKFILE_DIR }}/daemon.json  {{ .CONFIG_DIR }}/daemon.json
  default:
    cmds:
      - task -l
    silent: true
