---
version: '3'

dotenv:
  - .env

tasks:
  own:
    desc: Have gitea own the config file.
    preconditions:
      - test -f {{ .CONFIG_DIR }}/app.ini
      - getent passwd gitea
      - getent group gitea
    cmds:
      - chown gitea:gitea {{ .CONFIG_DIR }}/app.ini
  export:
    silent: true
    desc: Export the task list
    cmds:
      - task --list > task-list.txt
  status:
    desc: Status
    cmds:
      - systemctl status {{ .SERVICE_NAME }}.service
  init:
    desc: Init
    cmds:
      - cp .env.tmpl .env
  decrypt:
    desc: Decrypt .env using SOPS
    preconditions:
      - test -f {{ .TASKFILE_DIR }}/.env.enc
      - test -f {{ .TASKFILE_DIR }}/app.ini.enc
    cmds:
      - sops -d --input-type dotenv --output-type dotenv {{ .TASKFILE_DIR }}/.env.enc > {{ .TASKFILE_DIR }}/.env
      - sops -d --input-type ini --output-type ini {{ .TASKFILE_DIR }}/app.ini.enc | sudo tee {{ .CONFIG_DIR }}/app.ini
      - task: own
  encrypt:
    desc: Encrypt .env using SOPS
    preconditions:
      - test -f {{ .TASKFILE_DIR }}/.env
      - test -f {{ .CONFIG_DIR }}/app.ini
    cmds:
      - sops -e --input-type dotenv --output-type dotenv .env > .env.enc
      - sops -e --input-type ini --output-type ini {{ .CONFIG_DIR }}/app.ini > app.ini.enc
  update:
    desc: Update running containers
    preconditions:
      - test -f {{ .TASKFILE_DIR }}/update.sh
    cmds:
      - ./update.sh
      # - bash -c "$(wget -qLO - https://github.com/community-scripts/ProxmoxVE/raw/main/ct/gitea.sh)"
  upgrade:
    desc: Upgrade app
    cmds:
      - git pull origin
      - task: update
  stop:
    desc: Stop service
    cmds:
      - systemctl stop {{ .SERVICE_NAME }}.service
  restart:
    desc: Restart service
    cmds:
      - systemctl restart {{ .SERVICE_NAME }}.service
  default:
    cmds:
      - task -l
    silent: true
