---

services:
  shlink:
    container_name: shlink-backend
    image: shlinkio/shlink:4.6.0
    env_file:
      - .env
    environment:
      - DEFAULT_DOMAIN=localhost:8080
      - IS_HTTPS_ENABLED=false
      - GEOLITE_LICENSE_KEY=${GEOLITE_LICENSE_KEY}
      - SHELL_VERBOSITY=3
    ports:
      - '8080:8080'
    restart: always

  shlink-web-client:
    image: shlinkio/shlink-web-client
    restart: always
    container_name: shlink-frontend
    environment:
      - SHLINK_SERVER_URL=localhost:8080
      # - SHLINK_SERVER_API_KEY=
    depends_on:
      - shlink
    ports:
      - 8081:8080
