---
version: '3'

dotenv:
  - .env

tasks:
  export:
    silent: true
    desc: Export the task list to `task-list.txt`.
    cmds:
      - task --list > task-list.txt
  gen:
    desc: Generate an api key
    cmds:
      - " docker exec shlink-backend shlink api-key:generate"
  status:
    desc: Check the status of the application's service or Docker containers.
    cmds:
      - systemctl status {{ .SERVICE_NAME }}.service
  init:
    desc: Initialize the application's environment and configuration files.
    cmds:
      - cp .env.tmpl .env
  decrypt:
    desc: Decrypt sensitive configuration files using SOPS.
    cmds:
      - sops -d --input-type dotenv --output-type dotenv .env.enc > .env
  encrypt:
    desc: Encrypt sensitive configuration files using SOPS.
    cmds:
      - sops -e .env > .env.enc
  update:
    desc: Update the application or its running containers.
    cmds:
      - docker compose up --force-recreate --build -d
      - docker image prune -a -f
  up:
    desc: Run Docker Compose in the foreground.
    cmds:
      - docker compose up
  up-d:
    desc: Run Docker Compose in the background.
    cmds:
      - docker compose up -d --remove-orphans
  restart:
    desc: Restart the application's Docker containers.
    cmds:
      - "docker compose restart"
  upgrade:
    desc: Upgrade the application by pulling the latest changes and updating.
    cmds:
      - git pull origin
      - task: update
  stop:
    desc: Stop the application's Docker containers.
    cmds:
      - docker compose stop
  watch:
    desc: Watch the application's Docker container logs.
    cmds:
      - docker compose logs -f
  mklinks:
    desc: Create symbolic links for configuration files.
    cmds:
      - ln -sf {{ .TASKFILE_DIR }}/daemon.json  {{ .CONFIG_DIR }}/daemon.json
  default:
    cmds:
      - task -l
    silent: true
    desc: List all available tasks.
