---
version: '3'

dotenv:
  - .env

tasks:
  create-template:
    desc: Create template from existing .env file
    preconditions:
      - test -f .env
    cmds:
      - "sed '/^ *#/! s/=.*/=/' .env > .env.tmpl"
  decrypt:
    desc: Decrypt sensitive configuration files using SOPS.
    preconditions:
      - test -f .env.enc
    cmds:
      - sops -d --input-type dotenv --output-type dotenv .env.enc > .env
  enable:
    desc: Enable the application's systemd service.
    cmds:
      - systemctl enable {{ .SERVICE_NAME }}.service
  encrypt:
    desc: Encrypt sensitive configuration files using SOPS.
    preconditions:
      - test -f .env
    cmds:
      - sops -e .env > .env.enc
  export:
    silent: true
    desc: Export the task list to `task-list.txt`.
    cmds:
      - task --list > task-list.txt
  init:
    desc: Initialize the application's environment and configuration files.
    preconditions:
      - test -f .env.tmpl
    cmds:
      - cp .env.tmpl .env
  stow:
    desc: Create symbolic links for caddy files.
    cmds:
      - sudo stow -v -t {{ .CONFIG_DIR }} caddy
  mklinks:
    desc: Create symbolic links for configuration files.
    cmds:
      - task: stow
  restart:
    desc: Restart the application's systemd service.
    cmds:
      - sudo systemctl restart {{ .SERVICE_NAME }}.service
  start:
    desc: Start the application's systemd service.
    cmds:
      - sudo systemctl start {{ .SERVICE_NAME }}.service
  status:
    desc: Check the status of the application's systemd service.
    cmds:
      - sudo systemctl status {{ .SERVICE_NAME }}.service
  stop:
    desc: Stop the application's systemd service.
    cmds:
      - sudo systemctl stop {{ .SERVICE_NAME }}.service
  update:
    desc: Update the application or its running containers.
    cmds:
      - task: stop
      - git -C {{ .INSTALL_DIR }} pull origin
      - pnpm -C {{ .INSTALL_DIR }} run generate
      - task: start
      - task: status
  upgrade:
    desc: Upgrade the application by pulling the latest changes and updating.
    cmds:
      - git pull origin
      - task: update
  verify-secrets:
    desc: Checks if the decrypted secret matches the local file
    cmds:
      - echo "Secrets are in sync. Proceeding..."
    preconditions:
      - sh: diff -q .env <(sops -d --input-type dotenv --output-type dotenv .env.enc)
        msg: "The encrypted file and unencrypted file do not match! Please re-encrypt your changes."
  logs:
    desc: Show caddy logs
    cmds:
      - sudo journalctl -xeu {{ .SERVICE_NAME }}
  default:
    cmds:
      - task -l
    silent: true
    desc: List all available tasks.
