version: '3'
dotenv:
  - .env
tasks:
  create-template:
    desc: Create template from existing .env file
    preconditions:
      - test -f .env
    cmds:
      - sed '/^ *#/! s/=.*/=/' .env > .env.tmpl
  decrypt:
    desc: Decrypt sensitive configuration files using SOPS.
    preconditions:
      - test -f {{ .TASKFILE_DIR }}/.env.enc
      - test -f {{ .TASKFILE_DIR }}/frontend/.env.enc
      - test -f {{ .TASKFILE_DIR }}/backend/.env.enc
      - test -f {{ .TASKFILE_DIR }}/patchmon.creds.enc
    cmds:
      - sops -d --input-type dotenv --output-type dotenv {{ .TASKFILE_DIR }}/.env.enc
        > {{ .TASKFILE_DIR }}/.env
      - sops -d --input-type dotenv --output-type dotenv {{ .TASKFILE_DIR }}/frontend/.env.enc
        > {{ .TASKFILE_DIR }}/frontend/.env
      - sops -d --input-type dotenv --output-type dotenv {{ .TASKFILE_DIR }}/backend/.env.enc
        > {{ .TASKFILE_DIR }}/backend/.env
      - sops -d {{ .TASKFILE_DIR }}/patchmon.creds.enc > {{ .TASKFILE_DIR }}/patchmon.creds
  enable:
    desc: Enable the application's systemd service.
    cmds:
      - sudo systemctl enable -q --now {{ .SERVICE_NAME }}
  encrypt:
    desc: Encrypt sensitive configuration files using SOPS.
    cmds:
      - sops -e --input-type dotenv --output-type dotenv {{ .TASKFILE_DIR }}/.env
        > {{ .TASKFILE_DIR }}/.env.enc
      - sops -e --input-type dotenv --output-type dotenv {{ .TASKFILE_DIR }}/frontend/.env
        > {{ .TASKFILE_DIR }}/frontend/.env.enc
      - sops -e --input-type dotenv --output-type dotenv {{ .TASKFILE_DIR }}/backend/.env
        > {{ .TASKFILE_DIR }}/backend/.env.enc
      - sops -e {{ .TASKFILE_DIR }}/patchmon.creds > {{ .TASKFILE_DIR }}/patchmon.creds.enc
  export:
    silent: true
    desc: Export the task list to `task-list.txt`.
    cmds:
      - task --list > task-list.txt
  backup:
    desc: Run the Redis backup script and encrypt the dump file.
    preconditions:
      - test -f {{ .TASKFILE_DIR }}/backup.sh
    cmds:
      - sudo {{ .TASKFILE_DIR }}/backup.sh
  init:
    desc: Initialize the application's environment and configuration files.
    preconditions:
      - test -f .env.tmpl
    cmds:
      - cp .env.tmpl .env
  mklinks:
    desc: Create symbolic links for configuration files.
    preconditions:
      - test -d {{ .CONFIG_DIR }}
    cmds:
      - ln -sf {{ .TASKFILE_DIR }}/daemon.json  {{ .CONFIG_DIR }}/daemon.json
  restart:
    desc: Restart the application's systemd service.
    cmds:
      - sudo systemctl restart {{ .SERVICE_NAME }}.service
  start:
    desc: Start the application's systemd service.
    cmds:
      - sudo systemctl start {{ .SERVICE_NAME }}.service
  status:
    desc: Check the status of the application's systemd service.
    cmds:
      - sudo systemctl status {{ .SERVICE_NAME }}.service
  stop:
    desc: Stop the application's systemd service.
    cmds:
      - sudo systemctl stop {{ .SERVICE_NAME }}.service
  update:
    desc: Update the application or its running containers.
    preconditions:
      - test -f update.sh
    cmds:
      - sudo ./update.sh
  upgrade:
    desc: Upgrade the application by pulling the latest changes and updating.
    cmds:
      - git pull origin
      - task: update
  verify-secrets:
    desc: Checks if the decrypted secrets match the local files
    cmds:
      - echo "Secrets are in sync. Proceeding..."
    preconditions:
      - sh: diff -q {{ .TASKFILE_DIR }}/.env <(sops -d --input-type dotenv --output-type
          dotenv {{ .TASKFILE_DIR }}/.env.enc)
        msg: The encrypted .env file and unencrypted .env file do not match! Please
          re-encrypt your changes.
      - sh: diff -q {{ .TASKFILE_DIR }}/frontend/.env <(sops -d --input-type dotenv
          --output-type dotenv {{ .TASKFILE_DIR }}/frontend/.env.enc)
        msg: The encrypted frontend/.env file and unencrypted frontend/.env file do
          not match! Please re-encrypt your changes.
      - sh: diff -q {{ .TASKFILE_DIR }}/backend/.env <(sops -d --input-type dotenv
          --output-type dotenv {{ .TASKFILE_DIR }}/backend/.env.enc)
        msg: The encrypted backend/.env file and unencrypted backend/.env file do
          not match! Please re-encrypt your changes.
      - sh: diff -q {{ .TASKFILE_DIR }}/patchmon.creds <(sops -d {{ .TASKFILE_DIR
          }}/patchmon.creds.enc)
        msg: The encrypted patchmon.creds file and unencrypted patchmon.creds file
          do not match! Please re-encrypt your changes.
  service:install:
    desc: Install service
    preconditions:
      - test -f {{ .TASKFILE_DIR }}/{{ .SERVICE_NAME }}.service
    cmds:
      - sudo cp {{ .TASKFILE_DIR }}/{{ .SERVICE_NAME }}.service /etc/systemd/system/
      - task: enable
  settings:install:
    desc: Install settings
    preconditions:
      - test -f {{ .TASKFILE_DIR }}/update-settings.js
    cmds:
      - sudo cp {{ .TASKFILE_DIR }}/update-settings.js /opt/patchmon/backend/update-settings.js
      - node update-settings.js
  default:
    cmds:
      - task -l
    silent: true
    desc: List all available tasks.
