---
version: '3'

tasks:
  init:
    desc: Init
    cmds:
      - 'echo "$(pwd)/update.sh" > /usr/local/bin/update'
      - 'chmod +x /usr/local/bin/update'
  update:
    desc: Update WakeYourLAN
    cmds:
     - ./update.sh
  export:
    silent: true
    desc: Export the task list
    cmds:
      - task --list > task-list.txt
  stop:
    desc: Stop the service
    cmds:
      - service watchyourlan stop
  restart:
    desc: Restart the service
    cmds:
      - service watchyourlan restart
  encrypt:
    desc: Encrypt scan.db using SOPS
    cmds:
      - sops -e scan.db > scan.db.enc
  decrypt:
    desc: Decrypt scan.db using SOPS
    cmds:
      - sops -d scan.db.enc > scan.db
  mklinks:
    desc: Make soft links
    cmds:
      - task: stop
      - task: decrypt
      - ln -s /root/git/nicholaswilde/homelab/pve/watchyourlan/scan.db /etc/watchyourlan/scan.db
      - ln -s /root/git/nicholaswilde/homelab/pve/watchyourlan/config_v2.yaml /etc/watchyourlan/config_v2.yaml
      - task: restart
  verify-secrets:
    desc: Checks if the decrypted secrets match the local files
    cmds:
      - echo "Secrets are in sync. Proceeding..."
    preconditions:
      - sh: diff -q scan.db <(sops -d scan.db.enc)
        msg: "The encrypted scan.db file and unencrypted scan.db file do not match! Please re-encrypt your changes."
  default:
    cmds:
      - task -l
    silent: true
