---
version: '3'

tasks:
  update:
    desc: Update WakeYourLAN
    cmds:
     - ./update.sh
  export:
    desc: Export the task list
    cmds:
      - task --list > task-list.txt
  stop:
    desc: Stop the service
    cmds:
      - service watchyourlan stop
  restart:
    desc: Restart the service
    cmds:
      - service watchyourlan restart
  encrypt:
    desc: Encrypt scan.db using SOPS
    cmds:
      - sops -e scan.db > scan.db.enc
  decrypt:
    desc: Decrypt scan.db using SOPS
    cmds:
      - sops -d scan.db.enc > scan.db
  mklinks:
    desc: Make soft links
    cmds:
      - task: stop
      - task: decrypt
      - ln -s /root/git/nicholaswilde/homelab/pve/watchyourlan/scan.db /etc/watchyourlan/scan.db
      - ln -s /root/git/nicholaswilde/homelab/pve/watchyourlan/config_v2.yaml /etc/watchyourlan/config_v2.yaml
      - task: restart
  default:
    cmds:
      - task -l
    silent: true
