---
services:
  neovim-builder-amd64:
    build:
      context: .
      args:
        BASE_IMAGE: ubuntu:jammy
    platform: linux/amd64
    volumes:
      - ./dist:/dist

  neovim-builder-arm64:
    build:
      context: .
      args:
        BASE_IMAGE: arm64v8/ubuntu:jammy
    platform: linux/arm64
    volumes:
      - ./dist:/dist

  neovim-builder-armhf:
    build:
      context: .
      args:
        BASE_IMAGE: arm32v7/ubuntu:jammy
    platform: linux/arm/v7
    volumes:
      - ./dist:/dist
