---
version: '3'

tasks:
  deps:
    desc: Install deps
    cmds:
      -  docker run --privileged --rm tonistiigi/binfmt --install all
  arm64:
    desc: Build arm64
    cmds:
      - task: deps
      - docker compose --env-file ../.env up neovim-builder-arm64 --build --remove-orphans
  armhf:
    desc: Build armhf
    cmds:
      - task: deps
      - docker compose --env-file ../.env up neovim-builder-armhf --build --remove-orphans
  start:
    desc: Start test Docker image
    cmds:
      - docker compose up -d --build
  stop:
    desc: Stop test docker image
    cmds:
      - docker compose down
  restart:
    desc: Restart test Docker image
    cmds:
      - task: start
  rebuild:
    desc: Rebuild Docker containers
    cmds:
      - docker compose up -d --build
  build-neovim:
    desc: Build neovim
    cmds:
      - docker compose --env-file ../.env up --build
  default:
    cmds:
      - task -l
    silent: true
