---
version: '3'

tasks:
  start:
    desc: Start test Docker image
    cmds:
      - docker compose up -d --build
  stop:
    desc: Stop test docker image
    cmds:
      - docker compose down
  restart:
    desc: Restart test Docker image
    cmds:
      - task: start
  rebuild:
    desc: Rebuild Docker containers
    cmds:
      - docker compose up -d --build
  build-neovim:
    desc: Build neovim
    cmds:
      - docker compose --env-file ../.env up neovim-builder-amd64 --build
  default:
    cmds:
      - task -l
    silent: true
