# projects/restic/Taskfile.yml
version: '3'

vars:
  ROOT: "{{.TASKFILE_DIR}}/../.."
  PROJECT_NAME: sops
  REPO_URL: https://github.com/getsops/sops.git
  MAIN_PATH: ./cmd/sops
  VERSION_TAG: v3.11.0

tasks:
  check:
    desc: Verify the metadata of .deb files for this app only
    cmds:
      - cmd: |
          echo "Checking artifacts for {{.PROJECT_NAME}} in ../../dist/..."
          echo "---------------------------------------------------"
          
          # FIX: Filter by Project Name
          # We use "ls" first to handle the case where no files exist without crashing the loop
          files=$(ls ../../dist/{{.PROJECT_NAME}}*.deb 2>/dev/null)

          if [ -z "$files" ]; then
            echo "⚠️  No .deb files found for {{.PROJECT_NAME}}."
            exit 0
          fi

          for f in $files; do
            echo "📦 $(basename $f)"
            dpkg --info "$f" | grep -E "^ (Package|Version|Architecture):"
            echo "---------------------------------------------------"
          done
  latest:
    desc: Check the latest version available on GitHub
    cmds:
      - cmd: |
          LATEST=$(git ls-remote --tags --refs --sort="v:refname" {{.REPO_URL}} | tail -n1 | sed 's/.*\///')
          echo "Current Configured Version: {{.VERSION_TAG}}"
          echo "Latest Upstream Version:    $LATEST"
        silent: true
  build:
    desc: Build Restic (Go)
    # FIX: Define environment variables here. 
    # They are automatically exported to all cmds below.
    env:
      PROJECT_NAME: "{{.PROJECT_NAME}}"
      MAIN_PATH: "{{.MAIN_PATH}}"
      VERSION_TAG: "{{.VERSION_TAG}}"

    cmds:
      - echo "Building {{.PROJECT_NAME}}..."
      - rm -rf {{.ROOT}}/build/{{.PROJECT_NAME}}
      - git clone --depth 1 --branch {{.VERSION_TAG}} {{.REPO_URL}} {{.ROOT}}/build/{{.PROJECT_NAME}}

      - cmd: |
          cd {{.ROOT}}/build/{{.PROJECT_NAME}}
          
          # Now we just run the command. The variables are already in the air.
          goreleaser release --config {{.ROOT}}/templates/goreleaser-main.yaml --snapshot --clean --skip=publish

      - mkdir -p {{.ROOT}}/dist
      - mv {{.ROOT}}/build/{{.PROJECT_NAME}}/dist/*.deb {{.ROOT}}/dist/
      - echo "✅ Restic build complete."
  default:
    cmds:
      - task -l
    silent: true
