---
version: '3'

dotenv:
  - .env

tasks:
  export:
    silent: true
    desc: Export the task list
    cmds:
      - task --list > task-list.txt
  enable:
    desc: Enable service
    cmds:
      - systemctl enable {{ .SERVICE_NAME }}.service
  status:
    desc: Service status
    cmds:
      - systemctl status {{ .SERVICE_NAME }}.service
  init:
    desc: Init
    cmds:
      - cp .env.tmpl .env
  decrypt:
    desc: Decrypt .env using SOPS
    cmds:
      - sops -d --input-type dotenv --output-type dotenv .env.enc > .env
  encrypt:
    desc: Encrypt .env using SOPS
    cmds:
      - sops -e .env > .env.enc
  update:
    desc: Update running containers
    cmds:
      - ./update.sh
  
  restart:
    desc: Resart service
    cmds:
      - systemctl restart {{ .SERVICE_NAME }}.service
  upgrade:
    desc: upgrade
    cmds:
      - git pull origin
      - task: update
  stop:
    desc: Stop service
    cmds:
      - systemctl stop {{ .SERVICE_NAME }}.service
  start:
    desc: Start service
    cmds:
      - systemctl start {{ .SERVICE_NAME }}.service
  mklinks:
    desc: Make client symlinks
    cmds:
      - ln -sf {{ .TASKFILE_DIR }}/daemon.json  {{ .CONFIG_DIR }}/daemon.json
  default:
    cmds:
      - task -l
    silent: true
