---
version: '3'

dotenv:
  - .env

tasks:
  decrypt:
    desc: Decrypt .env using SOPS
    preconditions:
      - test -f .env.enc
      - test -f AdGuardHome.yaml.enc
    cmds:
      - sops -d --input-type dotenv --output-type dotenv .env.enc > .env
      - sops -d --input-type yaml --output-type yaml AdGuardHome.yaml.enc > AdGuardHome.yaml
  enable:
    desc: Enable the application's systemd service.
    cmds:
      - systemctl enable {{ .SERVICE_NAME }}.service
  encrypt:
    desc: Encrypt .env using SOPS
    preconditions:
      - test -f AdGuardHome.yaml
      - test -f .env
    cmds:
      - sops -e .env > .env.enc
      - sops -e --input-type yaml --output-type yaml AdGuardHome.yaml > AdGuardHome.yaml.enc
  export:
    silent: true
    desc: Export the task list to `task-list.txt`.
    cmds:
      - task --list > task-list.txt
  init:
    desc: Init
    cmds:
      - cp .env.tmpl .env
  mklinks:
    desc: Make client symlinks
    cmds:
      - ln -sf {{ .TASKFILE_DIR }}/daemon.json  {{ .CONFIG_DIR }}/daemon.json
  restart:
    desc: Resart service
    cmds:
      - systemctl restart {{ .SERVICE_NAME }}.service
  start:
    desc: Start service
    cmds:
      - systemctl start {{ .SERVICE_NAME }}.service
  status:
    desc: Check the status of the application's systemd service.
    cmds:
      - systemctl status {{ .SERVICE_NAME }}.service
  stop:
    desc: Stop service
    cmds:
      - systemctl stop {{ .SERVICE_NAME }}.service
  upgrade:
    desc: upgrade
    cmds:
      - git pull origin
      - task: update
  verify-secrets:
    desc: Checks if the decrypted secrets match the local files
    cmds:
      - echo "Secrets are in sync. Proceeding..."
    preconditions:
      - sh: diff -q .env <(sops -d --input-type dotenv --output-type dotenv .env.enc)
        msg: "The encrypted .env file and unencrypted .env file do not match! Please re-encrypt your changes."
      - sh: diff -q AdGuardHome.yaml <(sops -d --input-type yaml --output-type yaml AdGuardHome.yaml.enc)
        msg: "The encrypted AdGuardHome.yaml file and unencrypted AdGuardHome.yaml file do not match! Please re-encrypt your changes."
  backup:
    desc: Backs up the AdGuardHome.yaml file
    cmds:
      - ./backup-adguardhome.sh
  bt:install:
    desc: Install and enable the backup timer systemd service.
    cmds:
      - sudo cp {{.TASKFILE_DIR}}/backup.service.tmpl /etc/systemd/system/adguardhome-backup.service
      - sudo cp {{.TASKFILE_DIR}}/backup.timer.tmpl /etc/systemd/system/adguardhome-backup.timer
      - sudo systemctl daemon-reload
      - sudo systemctl enable --now adguardhome-backup.timer
    preconditions:
      - test -f {{.TASKFILE_DIR}}/backup.service.tmpl
      - test -f {{.TASKFILE_DIR}}/backup.timer.tmpl
  bt:uninstall:
    desc: Uninstall the backup timer systemd service.
    cmds:
      - sudo systemctl disable --now adguardhome-backup.timer
      - sudo rm /etc/systemd/system/adguardhome-backup.service
      - sudo rm /etc/systemd/system/adguardhome-backup.timer
      - sudo systemctl daemon-reload
  bt:status:
    desc: Check the status of the backup timer.
    cmds:
      - sudo systemctl status adguardhome-backup.timer
  bt:start:
    desc: Start the backup timer.
    cmds:
      - sudo systemctl start adguardhome-backup.timer
  bt:stop:
    desc: Stop the backup timer.
    cmds:
      - sudo systemctl stop adguardhome-backup.timer
  bt:enable:
    desc: Enable the backup timer to start on boot.
    cmds:
      - sudo systemctl enable adguardhome-backup.timer
  bt:disable:
    desc: Disable the backup timer from starting on boot.
    cmds:
      - sudo systemctl disable adguardhome-backup.timer
  default:
    cmds:
      - task -l
    silent: true