---
version: '3'

dotenv:
  - .env

tasks:
  decrypt:
    desc: Decrypt .env using SOPS
    preconditions:
      - test -f .env.enc
      - test -f AdGuardHome.yaml.enc
    cmds:
      - sops -d --input-type dotenv --output-type dotenv .env.enc > .env
      - sops -d --input-type yaml --output-type yaml AdGuardHome.yaml.enc > AdGuardHome.yaml
  enable:
    desc: Enable the application's systemd service.
    cmds:
      - systemctl enable {{ .SERVICE_NAME }}.service
  encrypt:
    desc: Encrypt .env using SOPS
    preconditions:
      - test -f AdGuardHome.yaml
      - test -f .env
    cmds:
      - sops -e .env > .env.enc
      - sops -e --input-type yaml --output-type yaml AdGuardHome.yaml > AdGuardHome.yaml.enc
  export:
    silent: true
    desc: Export the task list to `task-list.txt`.
    cmds:
      - task --list > task-list.txt
  init:
    desc: Init
    cmds:
      - cp .env.tmpl .env
  mklinks:
    desc: Make client symlinks
    cmds:
      - ln -sf {{ .TASKFILE_DIR }}/daemon.json  {{ .CONFIG_DIR }}/daemon.json
  restart:
    desc: Resart service
    cmds:
      - systemctl restart {{ .SERVICE_NAME }}.service
  start:
    desc: Start service
    cmds:
      - systemctl start {{ .SERVICE_NAME }}.service
  status:
    desc: Check the status of the application's systemd service.
    cmds:
      - systemctl status {{ .SERVICE_NAME }}.service
  stop:
    desc: Stop service
    cmds:
      - systemctl stop {{ .SERVICE_NAME }}.service
  upgrade:
    desc: upgrade
    cmds:
      - git pull origin
      - task: update
  backup:
    desc: Backs up the AdGuardHome.yaml file
    cmds:
      - ./backup-adguardhome.sh
  default:
    cmds:
      - task -l
    silent: true
