---
version: '3'

dotenv:
  - .env

tasks:
  bootstrap:
    desc: Bootstrap {{ .SERVICE_NAME }}
    cmds:
      - task: init
      - task: install
      - task: install-service
      - task: start
  decrypt:
    desc: Decrypt sensitive configuration files using SOPS.
    cmds:
      - "[ -f .env.enc ] && sops -d --input-type dotenv --output-type dotenv .env.enc > .env"
      - sops -d --input-type yaml --output-type yaml adguardhome-sync.yaml.enc > adguardhome-sync.yaml
    ignore_error: true
  encrypt:
    desc: Encrypt sensitive configuration files using SOPS.
    cmds:
      - sops -e .env > .env.enc
      - sops -e adguardhome-sync.yaml > adguardhome-sync.yaml.enc
  export:
    silent: true
    desc: Export the task list to `task-list.txt`.
    cmds:
      - task --list > task-list.txt
  init:
    desc: Initialize the application's environment and configuration files.
    cmds:
      - cp .env.tmpl .env
  install:
    desc: Install {{ .SERVICE_NAME }}
    cmds:
      - "[ -d /opt/adguardhome-sync ] || mkdir -p /opt/adguardhome-sync"
      - "cd /opt/adguardhome-sync"
      - "curl https://installer.l.nicholaswilde.io/bakito/adguardhome-sync | bash"
  install-service:
    desc: Install the application's systemd service.
    cmds:
      - "cp ./adguardhome-sync.service /etc/systemd/system/"
      - "systemctl enable adguardhome-sync.service"
  restart:
    desc: Restart the application's systemd service.
    cmds:
      - systemctl restart {{ .SERVICE_NAME }}.service
  start:
    desc: Start the application's systemd service.
    cmds:
      - systemctl start {{ .SERVICE_NAME }}.service
  stop:
    desc: Stop the application's systemd service.
    cmds:
      - systemctl stop {{ .SERVICE_NAME }}.service
  default:
    cmds:
      - task -l
    silent: true
    desc: List all available tasks.
