---
version: '3'

tasks:
  venv-create:
    desc: Create a Python virtual environment
    cmds:
      - python3 -m venv .venv
  deps:
    desc: Install Python dependencies for scripts
    cmds:
      - ./.venv/bin/pip install -r requirements.txt
    deps:
      - venv-create
