---
version: '3'

tasks:
  venv-create:
    desc: Create a Python virtual environment using uv
    cmds:
      - uv venv {{.TASKFILE_DIR}}/.venv
  deps:
    desc: Install Python dependencies for scripts using uv
    cmds:
      - uv pip install -r {{.TASKFILE_DIR}}/requirements.txt --python {{.TASKFILE_DIR}}/.venv/bin/python
    deps:
      - venv-create
