version: '3'

vars:
  ROOT:
    sh: realpath -m "{{.TASKFILE_DIR}}/../.."
  
  PROJECT_NAME: cookcli
  BINARY_NAME: cook
  REPO_URL: https://github.com/cooklang/cookcli.git
  VERSION_TAG: v0.19.0
  
  CACHE_DIR: "{{.ROOT}}/.cache"
  DIST_DIR: "{{.ROOT}}/dist"
  BUILD_DIR: "{{.ROOT}}/build"

tasks:
  check:
    desc: Verify the metadata of .deb files for this app only
    cmds:
      - cmd: |
          echo "Checking artifacts for {{.PROJECT_NAME}} in ../../dist/..."
          echo "---------------------------------------------------"
          files=$(ls ../../dist/{{.PROJECT_NAME}}*.deb 2>/dev/null)

          if [ -z "$files" ]; then
            echo "âš ï¸  No .deb files found for {{.PROJECT_NAME}}."
            exit 0
          fi

          for f in $files; do
            echo "ðŸ“¦ $(basename $f)"
            dpkg --info "$f" | grep -E "^ (Package|Version|Architecture):"
            echo "---------------------------------------------------"
          done
    silent: true

  build:
    desc: "Build {{.PROJECT_NAME}} (Rust)"
    cmds:
      - echo "Building {{.PROJECT_NAME}}..."
      - rm -rf {{.BUILD_DIR}}/{{.PROJECT_NAME}} {{.CACHE_DIR}}
      - mkdir -p {{.CACHE_DIR}} {{.DIST_DIR}} {{.BUILD_DIR}}/stage
      
      - git clone --depth 1 --branch {{.VERSION_TAG}} {{.REPO_URL}} {{.BUILD_DIR}}/{{.PROJECT_NAME}}
      
      # --- FIX: Inject Cross.toml using safe block echo ---
      - cmd: |
          # Define the file path
          FILE="{{.BUILD_DIR}}/{{.PROJECT_NAME}}/Cross.toml"
          
          # Write the config line by line
          echo '[target.aarch64-unknown-linux-gnu]' > "$FILE"
          echo 'image = "ghcr.io/cross-rs/aarch64-unknown-linux-gnu:edge"' >> "$FILE"
          
          echo '[target.armv7-unknown-linux-gnueabihf]' >> "$FILE"
          echo 'image = "ghcr.io/cross-rs/armv7-unknown-linux-gnueabihf:edge"' >> "$FILE"
          
          echo '[target.arm-unknown-linux-gnueabihf]' >> "$FILE"
          echo 'image = "ghcr.io/cross-rs/arm-unknown-linux-gnueabihf:edge"' >> "$FILE"
          
          echo '[target.x86_64-unknown-linux-gnu]' >> "$FILE"
          echo 'image = "ghcr.io/cross-rs/x86_64-unknown-linux-gnu:edge"' >> "$FILE"

      # Compile Targets
      - task: process-target
        vars: {RUST: "x86_64-unknown-linux-gnu", GO: "amd64", DEB: "amd64"}
      - task: process-target
        vars: {RUST: "aarch64-unknown-linux-gnu", GO: "arm64", DEB: "arm64"}
      - task: process-target
        vars: {RUST: "armv7-unknown-linux-gnueabihf", GO: "arm_7", DEB: "armhf"}
      
      # Note: ARMv6 (RPi Zero) often fails on OpenSSL with cooklang.
      # If it fails, comment the next two lines out.
      - task: process-target
        vars: {RUST: "arm-unknown-linux-gnueabihf", GO: "arm_6", DEB: "armel"}

      - echo "âœ… {{.PROJECT_NAME}} build complete."

  # --- Internal Helpers ---
  
  process-target:
    internal: true
    cmds:
      - task: compile
        vars: {RUST_TARGET: "{{.RUST}}", GO_FOLDER: "linux_{{.GO}}"}
      - task: package
        vars: {GO_ARCH: "{{.GO}}", ARCH: "{{.DEB}}"}

  compile:
    internal: true
    dir: "{{.BUILD_DIR}}/{{.PROJECT_NAME}}"
    cmds:
      - echo "Building for {{.RUST_TARGET}}..."
      - cross build --release --target {{.RUST_TARGET}}
      - mkdir -p {{.CACHE_DIR}}/{{.GO_FOLDER}}
      # Using BINARY_NAME (cook)
      - cp target/{{.RUST_TARGET}}/release/{{.BINARY_NAME}} {{.CACHE_DIR}}/{{.GO_FOLDER}}/

  package:
    internal: true
    dir: "{{.BUILD_DIR}}/stage"
    cmds:
      - echo "Packaging {{.ARCH}}..."
      
      # Using BINARY_NAME (cook)
      - cp {{.CACHE_DIR}}/linux_{{.GO_ARCH}}/{{.BINARY_NAME}} ./binary

      - cmd: |
          echo 'name: "{{.PROJECT_NAME}}"' > nfpm.yaml
          echo 'arch: "{{.ARCH}}"' >> nfpm.yaml
          echo 'platform: "linux"' >> nfpm.yaml
          echo 'version: "{{.VERSION_TAG | replace "v" ""}}"' >> nfpm.yaml
          echo 'section: "default"' >> nfpm.yaml
          echo 'priority: "extra"' >> nfpm.yaml
          echo 'maintainer: "Homelab Admin <admin@local>"' >> nfpm.yaml
          echo 'description: "Homelab build of {{.PROJECT_NAME}}"' >> nfpm.yaml
          echo 'vendor: "Homelab"' >> nfpm.yaml
          echo 'homepage: "{{.REPO_URL}}"' >> nfpm.yaml
          echo 'license: "MIT"' >> nfpm.yaml
          echo 'contents:' >> nfpm.yaml
          echo '  - src: "./binary"' >> nfpm.yaml
          
          # Installs as /usr/bin/cook
          echo '    dst: "/usr/bin/{{.BINARY_NAME}}"' >> nfpm.yaml
          
          echo '    file_info:' >> nfpm.yaml
          echo '      mode: 0755' >> nfpm.yaml

          nfpm pkg --config nfpm.yaml --packager deb --target {{.DIST_DIR}}/{{.PROJECT_NAME}}_{{.VERSION_TAG}}_{{.ARCH}}.deb
          
          rm nfpm.yaml binary

  default:
    cmds:
      - task -l
    silent: true

  latest:
    desc: Check the latest version available on GitHub
    cmds:
      - cmd: |
          LATEST=$(git ls-remote --tags --refs --sort="v:refname" {{.REPO_URL}} | tail -n1 | sed 's/.*\///')
          echo "Current Configured Version: {{.VERSION_TAG}}"
          echo "Latest Upstream Version:    $LATEST"
        silent: true
