---
version: '3'

dotenv:
  - .env

tasks:
  export:
    desc: Export the task list
    cmds:
      - task --list > task-list.txt
  status:
    desc: Docker container status
    cmds:
      - docker compose ps
  watch:
    desc: Watch Docker container logs
    cmds:
      - docker compose logs -f
  pull:
    desc: Pull docker images
    cmds:
      - docker compose pull
  status:
    desc: Docker container status
    cmds:
      - docker container ps
  init:
    desc: Init .env file
    cmds:
      - cp .env.tmpl .env
  decrypt:
    desc: Decrypt .env using SOPS
    cmds:
      - sops -d --input-type dotenv --output-type dotenv .env.enc > .env
  encrypt:
    desc: Encrypt .env using SOPS
    cmds:
      - sops -e .env > .env.enc
  update:
    desc: Update running containers
    cmds:
      - docker compose up --force-recreate --build -d
      - docker image prune -a -f
  up:
    desc: Run Docker compose in the foreground.
    cmds:
      - docker compose up
  up-d:
    desc: Run Docker compose in the background.
    cmds:
      - docker compose up -d --remove-orphans
  restart:
    desc: Restart Docker containers
    cmds:
      - docker compose restart
  upgrade:
    desc: Upgrade Docker containers
    cmds:
      - git pull origin
      - task: update
  stop:
    desc: Stop Docker containers
    cmds:
      - docker compose stop
  default:
    cmds:
      - task -l
    silent: true
