---
services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v3.0.1
    container_name: ${CONTAINER_NAME}
    restart: always
    env_file:
      - .env
    ports:
      - "9925:9000"
    deploy:
      resources:
        limits:
          memory: 1000M
    volumes:
      - data:/app/data/
    environment:
      # Set Backend ENV Variables Here
      ALLOW_SIGNUP: "false"
      PUID: 0
      PGID: 0
      TZ: America/Los_Angeles
      BASE_URL: https://mealie.nicholaswilde.io
      # ALLOW_SIGNUP: true
      OIDC_AUTH_ENABLED: false
      OIDC_SIGNUP_ENABLED: true
      OIDC_CONFIGURATION_URL: http://authentik.l.nicholaswilde.io:9000/application/o/mealie/.well-known/openid-configuration
      SMTP_HOST: "smtp.gmail.com"
      SMTP_PORT: 465
      SMTP_AUTH_STRATEGY: "SSL"
      # https://offen.github.io/docker-volume-backup/
  backup: &backup_service
    image: offen/docker-volume-backup:v2.43.4
    environment: &backup_environment
      BACKUP_FILENAME: backup-%Y-%m-%dT%H-%M-%S.tar.gz
      BACKUP_LATEST_SYMLINK: backup-latest.tar.gz
      BACKUP_PRUNING_PREFIX: backup-
      BACKUP_RETENTION_DAYS: '14'
      AGE_PUBLIC_KEYS: "${AGE_PUBLIC_KEYS}"
      BACKUP_STOP_DURING_BACKUP_LABEL: service
    volumes:
      - data:/backup/my-app-backup:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${HOME}/backups:/archive
      # - /mnt/storage/backup/mealie:/archive
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
volumes:
  data:
