---
name: "terminus"

services:
  web:
    init: true
    build:
      context: .
    environment:
      HANAMI_PORT: ${HANAMI_PORT}
      API_URI: ${API_URI}
      DATABASE_URL: postgres://${PG_USER}:${PG_PASSWORD}@database:5432/${PG_DATABASE}
    ports:
      - "${HANAMI_PORT}:${HANAMI_PORT}"
    restart: unless-stopped
    volumes:
      - web-assets-screens:/app/public/assets/screens
      - web-uploads:/app/public/uploads
    depends_on:
      database:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: "1.0"

  database:
    image: postgres:17.5
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_DB: ${PG_DATABASE}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - "${PG_PORT}:${PG_PORT}"
    volumes:
      - database-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER} -d ${PG_DATABASE}"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: "1.0"

  # https://offen.github.io/docker-volume-backup/
  backup: &backup_service
    image: offen/docker-volume-backup:v2.43.4
    environment: &backup_environment
      BACKUP_FILENAME: backup-%Y-%m-%dT%H-%M-%S.tar.gz
      BACKUP_LATEST_SYMLINK: backup-latest.tar.gz
      BACKUP_PRUNING_PREFIX: backup-
      BACKUP_RETENTION_DAYS: '14'
      AGE_PUBLIC_KEYS: "${AGE_PUBLIC_KEYS}"
      BACKUP_STOP_DURING_BACKUP_LABEL: service
    volumes:
      - database-data:/backup/database-data:ro
      - web-assets-screens:/backup/web-assets-screens:ro
      - web-uploads:/backup/web-uploads:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${HOME}/backups:/archive
      # - /mnt/storage/backup/reactive-resume:/archive
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

volumes:
  database-data:
  web-assets-screens:
  web-uploads:

networks:
  default:
    name: homelab
    external: true