version: '3'
tasks:
  doctor:
    desc: Run the Overleaf Toolkit doctor to check the setup.
    dir: /opt/overleaf
    cmds:
      - bin/doctor
  export:
    silent: true
    desc: Export the task list to `task-list.txt`.
    cmds:
      - task --list > task-list.txt
  logs:
    desc: View the Overleaf application logs.
    dir: /opt/overleaf
    cmds:
      - bin/logs
  restart:
    desc: Stop then start the Overleaf Docker services.
    dir: /opt/overleaf
    cmds:
      - bin/stop
      - bin/start
  shell:
    desc: Open an interactive shell inside the Overleaf container.
    dir: /opt/overleaf
    cmds:
      - bin/shell
  start:
    desc: Start the Overleaf Docker services.
    dir: /opt/overleaf
    cmds:
      - bin/start
  status:
    desc: Check the status of the Overleaf Docker services.
    dir: /opt/overleaf
    cmds:
      - docker compose -f lib/docker-compose.yml ps
  stop:
    desc: Stop the Overleaf Docker services.
    dir: /opt/overleaf
    cmds:
      - bin/stop
  up:
    desc: Run Docker Compose in the foreground.
    dir: /opt/overleaf
    cmds:
      - bin/up
  up-d:
    desc: Run Docker Compose in the background.
    dir: /opt/overleaf
    cmds:
      - bin/up -d
  upgrade:
    desc: Upgrade Overleaf to the latest version.
    dir: /opt/overleaf
    cmds:
      - bin/upgrade
  backup-config:
    desc: Backup the Overleaf config directory.
    dir: /opt/overleaf
    cmds:
      - bin/backup-config ~/overleaf-config-backup
  update:
    desc: Update the application or its running containers.
    preconditions:
      - test -f update.sh
    cmds:
      - ./update.sh
  default:
    cmds:
      - task -l
    silent: true
    desc: List all available tasks.
