---
version: '3'

dotenv:
  - .env

tasks:
  export:
    silent: true
    desc: Export the task list
    cmds:
      - task --list > task-list.txt
  backup:
    desc: Backup ChangeDetection
    cmds:
      - "curl -I http://localhost:5000/backups/request-backup"
      # - "curl -I https://cd.l.nicholaswilde.io/backups/request-backup"
  init:
    desc: Init app
    cmds:
      - cp .env.tmpl .env
  encrypt:
    desc: Encrypt scan.db using SOPS
    cmds:
      - sops -e --input-type dotenv --output-type dotenv .env > .env.enc
      - sops -e secret.txt > secret.txt.enc
      - sops -e url-watches.json > url-watches.json.enc
  decrypt:
    desc: Decrypt scan.db using SOPS
    cmds:
      - sops -d --input-type dotenv --output-type dotenv .env.enc > .env
      - sops -d secret.txt.enc > secret.txt
      - sops -d --input-type json --output-type json url-watches.json.enc > url-watches.json
  start:
    desc: Start ChangeDetection service
    cmds:
      - systemctl start changedetection.service
  restart:
    desc: Restart ChangeDetection service
    cmds:
      - systemctl restart changedetection.service
  stop:
    desc: Stop changedetection service
    cmds:
      - systemctl stop changedetection.service
  mklinks:
    desc: Make symlinks
    cmds:
      - task: stop
      # - task: decrypt
      - ln -sf /root/git/nicholaswilde/homelab/pve/changedetection/secret.txt {{ .CONFIG_DIR }}
      - ln -sf /root/git/nicholaswilde/homelab/pve/changedetection/url-watches.json {{ .CONFIG_DIR }}
      - ln -sf /root/git/nicholaswilde/homelab/pve/changedetection/url-list-with-tags.txt {{ .CONFIG_DIR }}
      - ln -sf /root/git/nicholaswilde/homelab/pve/changedetection/url-list.txt {{ .CONFIG_DIR }}
      - task: restart
  deps:
    desc: Install dependencies
    cmds:
      - apt update && apt install apprise
  update:
    desc: Update ChangeDetection
    cmds:
     - ./update.sh
  upgrade:
    desc: Upgrade ChangeDetection
    cmds:
      - git pull origin
      - task: update
  verify-secrets:
    desc: Checks if the decrypted secrets match the local files
    cmds:
      - echo "Secrets are in sync. Proceeding..."
    preconditions:
      - sh: diff -q .env <(sops -d --input-type dotenv --output-type dotenv .env.enc)
        msg: "The encrypted .env file and unencrypted .env file do not match! Please re-encrypt your changes."
      - sh: diff -q secret.txt <(sops -d secret.txt.enc)
        msg: "The encrypted secret.txt file and unencrypted secret.txt file do not match! Please re-encrypt your changes."
      - sh: diff -q url-watches.json <(sops -d --input-type json --output-type json url-watches.json.enc)
        msg: "The encrypted url-watches.json file and unencrypted url-watches.json file do not match! Please re-encrypt your changes."
  clean:
    desc: Clean node_modules
    cmds:
      - rm -rf {{ CONFIG_DIR }}/node_modules/.* {{ CONFIG_DIR }}/node_modules/@*/.*
  default:
    cmds:
      - task -l
    silent: true
