---
version: '3'

env:
  INSTALL_DIR: "/opt/ventoy"

dotenv:
  - .env

tasks:
  deps:
    desc: Install dependencies
    cmds:
      - sudo apt install rsync libxml2-utils

  sync:
    desc: Sync ISO images with USB drive
    cmds:
      - rsync -avz /path/to/your/isos/ /media/yourusername/USBDRIVE/isos/

  cron:
    desc: Setup cron job
    cmds:
      - echo "0 2 * * * rsync -avz /path/to/your/isos/ /media/yourusername/USBDRIVE/isos/" | crontab -

  restart:
    desc: Restart Ventoy
    cmds:
      - service ventoy restart

  install:
    desc: Install Ventoy
    cmds:
      - ./install.sh

  up:
    desc: Start web server
    cmds:
      - task: serve

  serve:
    desc: Start web server
    dir: /opt/ventoy/
    cmds:
      - sudo bash -c {{ .INSTALL_DIR}}/VentoyWeb.sh -H {{ .VENTOY_HOST }}

  default:
    cmds:
      - task -l
    silent: true
