---
version: '3'

dotenv:
  - .env

tasks:
  mount:
    desc: Mount USB
    cmds:
      - mount -t auto {{ .VENTOY_USB }} {{ .VENTOY_MNT }}

  umount:
    desc: Unmount USB
    cmds:
      - umount {{ .VENTOY_MNT }}

  update:
    desc: Update Ventoy
    cmds:
      - task: remove
      - task: install
      - task: start

  remove:
    desc: Remove Ventoy
    cmds:
      - task: stop
      - rm -rf {{ .VENTOY_INSTALL_DIR }}

  deps:
    desc: Install dependencies
    cmds:
      - sudo apt install rsync libxml2-utils dosfstools cron

  sync:
    desc: Sync ISO images with USB drive
    cmds:
      - find {{ .VENTOY_SOURCE }} -type f -name "*.iso" -exec cp -u {} {{ .VENTOY_DEST }} \;
      
  cron:
    desc: Setup cron job
    cmds:
      - (crontab -l 2>/dev/null; echo "0 2 * * * find {{ .VENTOY_SOURCE }} -type f -name \"*.iso\" -exec cp {} {{ .VENTOY_DEST }} \;") | crontab -

  start:
    desc: Restart Ventoy
    cmds:
      - service ventoy start

  restart:
    desc: Restart Ventoy
    cmds:
      - service ventoy restart

  stop:
    desc: Stop Ventoy
    cmds:
      - service ventoy stop

  install:
    desc: Install Ventoy
    cmds:
      - ./install.sh

  up:
    desc: Start web server
    cmds:
      - task: serve

  serve:
    desc: Start web server
    dir: /opt/ventoy/
    cmds:
      - sudo bash -c {{ .INSTALL_DIR}}/VentoyWeb.sh -H {{ .VENTOY_HOST }}

  default:
    cmds:
      - task -l
    silent: true
