---
version: '3'

tasks:
  sync:
    desc: Sync ISO images with USB drive
    cmds:
      - rsync -avz /path/to/your/isos/ /media/yourusername/USBDRIVE/isos/
  cron:
    desc: Setup cron job
    cmds:
      - echo "0 2 * * * rsync -avz /path/to/your/isos/ /media/yourusername/USBDRIVE/isos/" | crontab -

  restart:
    desc: Restart Ventoy
    cmds:
      - service ventoy restart

  install:
    desc: Install Ventoy
    cmds:
      - ./install.sh

  up:
    desc: Start web server
    cmds:
      - task: serve

  serve:
    desc: Start web server
    cmds:
      - ./opt/ventoy/VentoyWeb.sh

  default:
    cmds:
      - task -l
    silent: true
